"""Curated cooking / food terms.

International dish names, ingredients, and food-brand names that
Whisper consistently mishears ("gnocchi" → "no key", "pho" → "fuh",
"bánh mì" → "bonn me", "biryani" → "biriyani").
"""

from __future__ import annotations

import logging
from typing import Iterable

from ..types import RawTerm

logger = logging.getLogger(__name__)


_TERMS: list[tuple[str, str, str]] = [
    # Italian
    ("gnocchi", "potato dumpling", "italian"),
    ("bruschetta", "grilled bread topped", "italian"),
    ("carbonara", "egg-pancetta pasta", "italian"),
    ("amatriciana", "tomato-pancetta pasta", "italian"),
    ("cacio e pepe", "cheese-pepper pasta", "italian"),
    ("puttanesca", "olive-caper pasta", "italian"),
    ("bolognese", "meat sauce", "italian"),
    ("pesto", "basil sauce", "italian"),
    ("ragù", "meat sauce", "italian"),
    ("ravioli", "stuffed pasta", "italian"),
    ("tortellini", "ring-shaped pasta", "italian"),
    ("lasagna", "layered pasta", "italian"),
    ("orecchiette", "ear-shaped pasta", "italian"),
    ("pappardelle", "wide ribbon pasta", "italian"),
    ("focaccia", "flat oven-baked bread", "italian"),
    ("ciabatta", "Italian bread", "italian"),
    ("biscotti", "twice-baked cookie", "italian"),
    ("tiramisu", "coffee dessert", "italian"),
    ("panna cotta", "cooked cream dessert", "italian"),
    ("mascarpone", "soft Italian cheese", "italian"),
    ("burrata", "mozzarella variant", "italian"),
    ("ricotta", "Italian whey cheese", "italian"),
    ("prosciutto", "dry-cured ham", "italian"),
    ("pancetta", "Italian cured pork belly", "italian"),
    ("guanciale", "cured pork jowl", "italian"),
    ("bresaola", "air-dried beef", "italian"),
    ("mortadella", "Italian sausage", "italian"),
    ("Parmigiano", "Parmesan cheese", "italian"),
    ("Parmigiano-Reggiano", "Italian hard cheese", "italian"),
    ("Pecorino", "Italian sheep cheese", "italian"),
    ("Asiago", "Italian cheese", "italian"),
    ("Provolone", "Italian cheese", "italian"),
    ("limoncello", "lemon liqueur", "italian"),
    ("amaro", "Italian herbal liqueur", "italian"),
    ("Aperol", "Italian aperitif", "italian"),
    ("Campari", "Italian aperitif", "italian"),
    # Asian
    ("pho", "Vietnamese noodle soup", "vietnamese"),
    ("bánh mì", "Vietnamese sandwich", "vietnamese"),
    ("banh mi", "Vietnamese sandwich", "vietnamese"),
    ("bún chả", "Vietnamese grilled pork", "vietnamese"),
    ("bún", "Vietnamese rice noodle", "vietnamese"),
    ("nước mắm", "Vietnamese fish sauce", "vietnamese"),
    ("ramen", "Japanese noodle soup", "japanese"),
    ("udon", "thick Japanese noodle", "japanese"),
    ("soba", "Japanese buckwheat noodle", "japanese"),
    ("yakitori", "Japanese grilled chicken skewers", "japanese"),
    ("sushi", "Japanese rice dish", "japanese"),
    ("sashimi", "raw fish slices", "japanese"),
    ("tempura", "battered fried", "japanese"),
    ("teriyaki", "Japanese glaze", "japanese"),
    ("miso", "fermented soybean paste", "japanese"),
    ("dashi", "Japanese stock", "japanese"),
    ("mirin", "Japanese sweet rice wine", "japanese"),
    ("nori", "edible seaweed", "japanese"),
    ("wasabi", "Japanese horseradish", "japanese"),
    ("yuzu", "Japanese citrus", "japanese"),
    ("matcha", "powdered green tea", "japanese"),
    ("mochi", "rice cake", "japanese"),
    ("dorayaki", "Japanese pancake-cake", "japanese"),
    ("taiyaki", "fish-shaped Japanese cake", "japanese"),
    ("kimchi", "Korean fermented vegetables", "korean"),
    ("bibimbap", "Korean rice bowl", "korean"),
    ("bulgogi", "Korean grilled beef", "korean"),
    ("japchae", "Korean stir-fried noodles", "korean"),
    ("tteokbokki", "Korean rice cake dish", "korean"),
    ("samgyeopsal", "Korean grilled pork belly", "korean"),
    ("gochujang", "Korean chili paste", "korean"),
    ("doenjang", "Korean fermented soybean paste", "korean"),
    ("biryani", "South Asian rice dish", "south_asian"),
    ("biriyani", "South Asian rice dish (alternate spelling)", "south_asian"),
    ("naan", "South Asian flatbread", "south_asian"),
    ("paratha", "South Asian flatbread", "south_asian"),
    ("dosa", "South Indian crepe", "south_asian"),
    ("idli", "South Indian rice cake", "south_asian"),
    ("samosa", "fried South Asian pastry", "south_asian"),
    ("chana masala", "chickpea curry", "south_asian"),
    ("dal", "South Asian lentil dish", "south_asian"),
    ("dahl", "alternate dal", "south_asian"),
    ("paneer", "South Asian cheese", "south_asian"),
    ("ghee", "clarified butter", "south_asian"),
    ("tikka masala", "spiced South Asian dish", "south_asian"),
    ("vindaloo", "spicy curry", "south_asian"),
    ("rogan josh", "Kashmiri curry", "south_asian"),
    ("korma", "creamy South Asian curry", "south_asian"),
    ("masala", "spice mix", "south_asian"),
    ("chai", "spiced tea", "south_asian"),
    ("lassi", "yogurt drink", "south_asian"),
    ("dim sum", "Chinese small dishes", "chinese"),
    ("xiaolongbao", "soup dumplings", "chinese"),
    ("baozi", "steamed buns", "chinese"),
    ("char siu", "Chinese BBQ pork", "chinese"),
    ("congee", "rice porridge", "chinese"),
    ("mapo tofu", "Sichuan tofu dish", "chinese"),
    ("kung pao chicken", "Sichuan dish", "chinese"),
    ("Sichuan", "Chinese region", "chinese"),
    ("Szechuan", "Chinese region", "chinese"),
    ("hoisin", "Chinese sauce", "chinese"),
    ("Shaoxing wine", "Chinese cooking wine", "chinese"),
    # Middle Eastern
    ("hummus", "chickpea spread", "middle_eastern"),
    ("falafel", "fried chickpea balls", "middle_eastern"),
    ("shawarma", "spit-roasted meat", "middle_eastern"),
    ("kebab", "skewered meat", "middle_eastern"),
    ("kofta", "ground meat", "middle_eastern"),
    ("dolma", "stuffed grape leaves", "middle_eastern"),
    ("tabbouleh", "parsley-bulgur salad", "middle_eastern"),
    ("baba ghanoush", "eggplant dip", "middle_eastern"),
    ("baba ganoush", "eggplant dip alternate spelling", "middle_eastern"),
    ("tahini", "sesame paste", "middle_eastern"),
    ("za'atar", "Middle Eastern spice", "middle_eastern"),
    ("sumac", "tart spice", "middle_eastern"),
    ("baklava", "sweet pastry", "middle_eastern"),
    ("kanafeh", "cheese pastry", "middle_eastern"),
    ("manakeesh", "Middle Eastern flatbread", "middle_eastern"),
    # French
    ("croissant", "French pastry", "french"),
    ("baguette", "French bread", "french"),
    ("pain au chocolat", "chocolate pastry", "french"),
    ("brioche", "rich French bread", "french"),
    ("ratatouille", "French vegetable stew", "french"),
    ("bouillabaisse", "French fish stew", "french"),
    ("coq au vin", "wine-braised chicken", "french"),
    ("cassoulet", "French slow-cooked stew", "french"),
    ("crêpe", "French thin pancake", "french"),
    ("crème brûlée", "burnt cream dessert", "french"),
    ("crème fraîche", "soured cream", "french"),
    ("foie gras", "duck/goose liver", "french"),
    ("escargot", "snails", "french"),
    ("hors d'oeuvre", "appetizer", "french"),
    ("amuse-bouche", "small bite", "french"),
    ("mille-feuille", "layered pastry", "french"),
    ("pain perdu", "French toast", "french"),
    ("Béarnaise", "egg butter sauce", "french"),
    ("Hollandaise", "egg butter sauce", "french"),
    ("Bordelaise", "red wine sauce", "french"),
    ("Provençal", "Provence-style", "french"),
    # Spanish / Latin
    ("paella", "Spanish rice dish", "spanish"),
    ("tapas", "Spanish small plates", "spanish"),
    ("jamón", "Spanish ham", "spanish"),
    ("Jamón Ibérico", "Iberian ham", "spanish"),
    ("Manchego", "Spanish sheep cheese", "spanish"),
    ("chorizo", "Spanish sausage", "spanish"),
    ("gazpacho", "cold Spanish soup", "spanish"),
    ("ceviche", "raw seafood dish", "latin"),
    ("empanada", "stuffed pastry", "latin"),
    ("arepa", "South American flatbread", "latin"),
    ("tamale", "corn dough dish", "latin"),
    ("mole", "Mexican sauce", "latin"),
    ("guacamole", "avocado dip", "latin"),
    ("birria", "Mexican stew", "latin"),
    ("barbacoa", "slow-cooked meat", "latin"),
    ("carnitas", "braised pork", "latin"),
    ("al pastor", "shawarma-style pork", "latin"),
    ("pozole", "Mexican stew", "latin"),
    ("Oaxaca", "Mexican region (cheese, mole)", "latin"),
    ("Oaxacan", "from Oaxaca", "latin"),
    ("tres leches", "three milks cake", "latin"),
    ("dulce de leche", "milk caramel", "latin"),
    ("alfajor", "South American cookie", "latin"),
    ("churro", "fried dough pastry", "latin"),
    # Brand names
    ("Cheerios", "cereal brand", "brand"),
    ("Frosted Flakes", "cereal brand", "brand"),
    ("Lucky Charms", "cereal brand", "brand"),
    ("Cap'n Crunch", "cereal brand", "brand"),
    ("Coca-Cola", "soft drink brand", "brand"),
    ("Pepsi", "soft drink brand", "brand"),
    ("Sprite", "soft drink", "brand"),
    ("Dr Pepper", "soft drink", "brand"),
    ("Mountain Dew", "soft drink", "brand"),
    ("Tim Hortons", "Canadian coffee chain", "brand"),
    ("Starbucks", "coffee chain", "brand"),
    ("Dunkin'", "coffee/donut chain", "brand"),
    ("Chick-fil-A", "fast food chain", "brand"),
    ("In-N-Out", "burger chain", "brand"),
    ("Trader Joe's", "grocery chain", "brand"),
    ("Whole Foods", "grocery chain", "brand"),
    ("Costco", "warehouse club", "brand"),
    ("Aldi", "grocery chain", "brand"),
    ("Lidl", "grocery chain", "brand"),
    ("Kraft", "food company", "brand"),
    ("Kellogg's", "food company", "brand"),
    ("General Mills", "food company", "brand"),
    ("Heinz", "food company", "brand"),
    ("Hershey's", "chocolate brand", "brand"),
    ("Cadbury", "chocolate brand", "brand"),
    ("Lindt", "chocolate brand", "brand"),
    ("Ghirardelli", "chocolate brand", "brand"),
    ("Häagen-Dazs", "ice cream brand", "brand"),
    ("Ben & Jerry's", "ice cream brand", "brand"),
    # Diet / dietary
    ("keto", "ketogenic diet", "diet"),
    ("paleo", "Paleolithic diet", "diet"),
    ("vegan", "no animal products", "diet"),
    ("vegetarian", "no meat", "diet"),
    ("pescatarian", "fish only meat", "diet"),
    ("flexitarian", "mostly plant", "diet"),
    ("FODMAP", "fermentable carbs", "diet"),
    ("gluten-free", "no wheat protein", "diet"),
    ("kosher", "Jewish dietary law", "diet"),
    ("halal", "Islamic dietary law", "diet"),
]


def iter_terms() -> Iterable[RawTerm]:
    seen: set[str] = set()
    for canonical, gloss, subcat in _TERMS:
        key = canonical.lower()
        if key in seen:
            continue
        seen.add(key)
        score = 0.65
        yield RawTerm(
            term=canonical,
            canonical_form=canonical,
            category="cooking",
            subcategory=subcat,
            context_blurb=gloss[:140],
            popularity_score=score,
            source="Curated cooking / food terms",
        )
    logger.info("Cooking / food: %d yielded", len(seen))


name = "Cooking / Food"
category = "cooking"
