"""Curated cooking / food terms.

International dish names, ingredients, and food-brand names that
Whisper consistently mishears ("gnocchi" → "no key", "pho" → "fuh",
"bánh mì" → "bonn me", "biryani" → "biriyani").
"""

from __future__ import annotations

import logging
from typing import Iterable

from ..types import RawTerm

logger = logging.getLogger(__name__)


# International dish names with non-English pronunciations Whisper
# consistently fumbles. Maps canonical → list of phonetic respellings.
_PRONUNCIATIONS: dict[str, list[str]] = {
    "gnocchi": ["nyoh kee", "nyokey", "nyohki", "no kee"],
    "bruschetta": ["broo sket uh"],
    "carbonara": ["kar boh nar uh"],
    "amatriciana": ["uh ma trih chee ah nuh"],
    "cacio e pepe": ["kah cho eh peh peh"],
    "puttanesca": ["poo tah nes kah"],
    "bolognese": ["boh loh nyay zay", "bol uh nez"],
    "pesto": ["pes toh"],
    "ragù": ["rah goo"],
    "ravioli": ["rav ee oh lee"],
    "tortellini": ["tor tuh lee nee"],
    "lasagna": ["luh zahn yuh"],
    "orecchiette": ["oh rek ee et eh"],
    "pappardelle": ["pap er del eh"],
    "focaccia": ["foh kah cha"],
    "ciabatta": ["chuh bah tuh"],
    "biscotti": ["bis kot ee"],
    "tiramisu": ["tih ruh mee soo"],
    "panna cotta": ["pah nuh kot uh"],
    "mascarpone": ["mas kar poh neh"],
    "burrata": ["boo rah tuh"],
    "ricotta": ["rih kot uh"],
    "prosciutto": ["proh shoo toh"],
    "pancetta": ["pan chet uh"],
    "guanciale": ["gwahn chah leh"],
    "bresaola": ["breh zow luh"],
    "mortadella": ["mor tuh del uh"],
    "Parmigiano": ["par mih jah noh"],
    "Parmigiano-Reggiano": ["par mih jah noh reh jah noh"],
    "Pecorino": ["pek oh ree noh"],
    "Asiago": ["ah see ah goh"],
    "Provolone": ["proh voh loh neh"],
    "limoncello": ["lim un chel oh"],
    "amaro": ["uh mar oh"],
    "Aperol": ["ah per ohl"],
    "Campari": ["kam par ee"],
    "pho": ["fuh", "fah", "fuh-ah"],
    "bánh mì": ["bahn mee", "bahn-mee"],
    "banh mi": ["bahn mee", "bahn-mee"],
    "bún chả": ["boon chah"],
    "bún": ["boon"],
    "nước mắm": ["nuk mahm", "nyook mahm"],
    "ramen": ["rah men"],
    "udon": ["oo don"],
    "soba": ["soh bah"],
    "yakitori": ["yah kih tor ee"],
    "sushi": ["soo shee"],
    "sashimi": ["sah shee mee"],
    "tempura": ["tem pyur uh"],
    "teriyaki": ["tair ih yah kee"],
    "miso": ["mee soh"],
    "dashi": ["dah shee"],
    "mirin": ["mih rin"],
    "nori": ["nor ee"],
    "wasabi": ["wuh sah bee"],
    "yuzu": ["yoo zoo"],
    "matcha": ["mah cha"],
    "mochi": ["moh chee"],
    "dorayaki": ["dor uh yah kee"],
    "taiyaki": ["tie yah kee"],
    "kimchi": ["kim chee"],
    "bibimbap": ["bee bim bap"],
    "bulgogi": ["bool goh gee"],
    "japchae": ["jap chay"],
    "tteokbokki": ["duck bok ee", "tuhk bok ee"],
    "samgyeopsal": ["sahm gyup sahl"],
    "gochujang": ["go choo jahng"],
    "doenjang": ["dwen jahng"],
    "biryani": ["beer yah nee", "bir yah nee"],
    "biriyani": ["beer ee yah nee"],
    "naan": ["nahn"],
    "paratha": ["puh rah tuh"],
    "dosa": ["doh sah"],
    "idli": ["id lee"],
    "samosa": ["suh moh sah"],
    "chana masala": ["chuh nuh muh sah luh"],
    "dal": ["dahl"],
    "dahl": ["dahl"],
    "paneer": ["puh neer"],
    "ghee": ["gee"],
    "tikka masala": ["tik uh muh sah luh"],
    "vindaloo": ["vin duh loo"],
    "rogan josh": ["roh gun josh"],
    "korma": ["kor mah"],
    "masala": ["muh sah luh"],
    "chai": ["chai", "chye"],
    "lassi": ["lah see"],
    "dim sum": ["dim sum"],
    "xiaolongbao": ["shyow long bow"],
    "baozi": ["bow zuh"],
    "char siu": ["char shoo"],
    "congee": ["kon jee"],
    "mapo tofu": ["mah poh toh foo"],
    "kung pao chicken": ["kung pow chick en"],
    "Sichuan": ["sich wahn", "sih chwahn"],
    "Szechuan": ["sech wahn"],
    "hoisin": ["hoy sin"],
    "Shaoxing wine": ["shao shing wine"],
    "hummus": ["hum us", "hoom us"],
    "falafel": ["fuh lah fel"],
    "shawarma": ["shuh war muh"],
    "kebab": ["kuh bab", "key bab"],
    "kofta": ["kof tah"],
    "dolma": ["dohl mah"],
    "tabbouleh": ["tuh boo lee"],
    "baba ghanoush": ["bah bah guh noosh"],
    "baba ganoush": ["bah bah guh noosh"],
    "tahini": ["tuh hee nee"],
    "za'atar": ["zah uh tar"],
    "sumac": ["soo mak"],
    "baklava": ["bahk luh vah"],
    "kanafeh": ["kuh nah feh"],
    "manakeesh": ["muh nuh keesh"],
    "croissant": ["kruh sahnt", "kwah sahn"],
    "baguette": ["bag et"],
    "pain au chocolat": ["pan oh shoh koh lah"],
    "brioche": ["bree ohsh"],
    "ratatouille": ["rat uh too ee"],
    "bouillabaisse": ["boo yuh base"],
    "coq au vin": ["kok oh van"],
    "cassoulet": ["kas oo lay"],
    "crêpe": ["krep", "krayp"],
    "crème brûlée": ["krem broo lay"],
    "crème fraîche": ["krem fresh"],
    "foie gras": ["fwah grah"],
    "escargot": ["es kar goh"],
    "hors d'oeuvre": ["or derv"],
    "amuse-bouche": ["uh muz boosh"],
    "mille-feuille": ["meel foy"],
    "pain perdu": ["pan per doo"],
    "Béarnaise": ["bair nayz"],
    "Hollandaise": ["hol un dayz"],
    "Bordelaise": ["bor duh layz"],
    "Provençal": ["proh vahn sahl"],
    "paella": ["pah ay yuh", "pi el uh"],
    "tapas": ["tah pus"],
    "jamón": ["hah mohn"],
    "Jamón Ibérico": ["hah mohn ee ber ee koh"],
    "Manchego": ["mahn chay goh"],
    "chorizo": ["chuh ree zoh", "chor ee soh"],
    "gazpacho": ["gah spah choh"],
    "ceviche": ["seh vee chay"],
    "empanada": ["em pan ah duh"],
    "arepa": ["uh ray pah"],
    "tamale": ["tuh mah lee"],
    "mole": ["moh lay"],
    "guacamole": ["gwah kuh moh lay"],
    "birria": ["beer ee uh"],
    "barbacoa": ["bar buh koh uh"],
    "carnitas": ["kar nee tus"],
    "al pastor": ["al pas tor"],
    "pozole": ["poh soh lay"],
    "Oaxaca": ["wuh hah kah"],
    "Oaxacan": ["wuh hah kun"],
    "tres leches": ["trace lay ches"],
    "dulce de leche": ["dool say day lay chay"],
    "alfajor": ["al fah hor"],
    "churro": ["chur oh"],
    "Häagen-Dazs": ["hah gun dahz"],
    "FODMAP": ["fod map"],
}


_TERMS: list[tuple[str, str, str]] = [
    # Italian
    ("gnocchi", "potato dumpling", "italian"),
    ("bruschetta", "grilled bread topped", "italian"),
    ("carbonara", "egg-pancetta pasta", "italian"),
    ("amatriciana", "tomato-pancetta pasta", "italian"),
    ("cacio e pepe", "cheese-pepper pasta", "italian"),
    ("puttanesca", "olive-caper pasta", "italian"),
    ("bolognese", "meat sauce", "italian"),
    ("pesto", "basil sauce", "italian"),
    ("ragù", "meat sauce", "italian"),
    ("ravioli", "stuffed pasta", "italian"),
    ("tortellini", "ring-shaped pasta", "italian"),
    ("lasagna", "layered pasta", "italian"),
    ("orecchiette", "ear-shaped pasta", "italian"),
    ("pappardelle", "wide ribbon pasta", "italian"),
    ("focaccia", "flat oven-baked bread", "italian"),
    ("ciabatta", "Italian bread", "italian"),
    ("biscotti", "twice-baked cookie", "italian"),
    ("tiramisu", "coffee dessert", "italian"),
    ("panna cotta", "cooked cream dessert", "italian"),
    ("mascarpone", "soft Italian cheese", "italian"),
    ("burrata", "mozzarella variant", "italian"),
    ("ricotta", "Italian whey cheese", "italian"),
    ("prosciutto", "dry-cured ham", "italian"),
    ("pancetta", "Italian cured pork belly", "italian"),
    ("guanciale", "cured pork jowl", "italian"),
    ("bresaola", "air-dried beef", "italian"),
    ("mortadella", "Italian sausage", "italian"),
    ("Parmigiano", "Parmesan cheese", "italian"),
    ("Parmigiano-Reggiano", "Italian hard cheese", "italian"),
    ("Pecorino", "Italian sheep cheese", "italian"),
    ("Asiago", "Italian cheese", "italian"),
    ("Provolone", "Italian cheese", "italian"),
    ("limoncello", "lemon liqueur", "italian"),
    ("amaro", "Italian herbal liqueur", "italian"),
    ("Aperol", "Italian aperitif", "italian"),
    ("Campari", "Italian aperitif", "italian"),
    # Asian
    ("pho", "Vietnamese noodle soup", "vietnamese"),
    ("bánh mì", "Vietnamese sandwich", "vietnamese"),
    ("banh mi", "Vietnamese sandwich", "vietnamese"),
    ("bún chả", "Vietnamese grilled pork", "vietnamese"),
    ("bún", "Vietnamese rice noodle", "vietnamese"),
    ("nước mắm", "Vietnamese fish sauce", "vietnamese"),
    ("ramen", "Japanese noodle soup", "japanese"),
    ("udon", "thick Japanese noodle", "japanese"),
    ("soba", "Japanese buckwheat noodle", "japanese"),
    ("yakitori", "Japanese grilled chicken skewers", "japanese"),
    ("sushi", "Japanese rice dish", "japanese"),
    ("sashimi", "raw fish slices", "japanese"),
    ("tempura", "battered fried", "japanese"),
    ("teriyaki", "Japanese glaze", "japanese"),
    ("miso", "fermented soybean paste", "japanese"),
    ("dashi", "Japanese stock", "japanese"),
    ("mirin", "Japanese sweet rice wine", "japanese"),
    ("nori", "edible seaweed", "japanese"),
    ("wasabi", "Japanese horseradish", "japanese"),
    ("yuzu", "Japanese citrus", "japanese"),
    ("matcha", "powdered green tea", "japanese"),
    ("mochi", "rice cake", "japanese"),
    ("dorayaki", "Japanese pancake-cake", "japanese"),
    ("taiyaki", "fish-shaped Japanese cake", "japanese"),
    ("kimchi", "Korean fermented vegetables", "korean"),
    ("bibimbap", "Korean rice bowl", "korean"),
    ("bulgogi", "Korean grilled beef", "korean"),
    ("japchae", "Korean stir-fried noodles", "korean"),
    ("tteokbokki", "Korean rice cake dish", "korean"),
    ("samgyeopsal", "Korean grilled pork belly", "korean"),
    ("gochujang", "Korean chili paste", "korean"),
    ("doenjang", "Korean fermented soybean paste", "korean"),
    ("biryani", "South Asian rice dish", "south_asian"),
    ("biriyani", "South Asian rice dish (alternate spelling)", "south_asian"),
    ("naan", "South Asian flatbread", "south_asian"),
    ("paratha", "South Asian flatbread", "south_asian"),
    ("dosa", "South Indian crepe", "south_asian"),
    ("idli", "South Indian rice cake", "south_asian"),
    ("samosa", "fried South Asian pastry", "south_asian"),
    ("chana masala", "chickpea curry", "south_asian"),
    ("dal", "South Asian lentil dish", "south_asian"),
    ("dahl", "alternate dal", "south_asian"),
    ("paneer", "South Asian cheese", "south_asian"),
    ("ghee", "clarified butter", "south_asian"),
    ("tikka masala", "spiced South Asian dish", "south_asian"),
    ("vindaloo", "spicy curry", "south_asian"),
    ("rogan josh", "Kashmiri curry", "south_asian"),
    ("korma", "creamy South Asian curry", "south_asian"),
    ("masala", "spice mix", "south_asian"),
    ("chai", "spiced tea", "south_asian"),
    ("lassi", "yogurt drink", "south_asian"),
    ("dim sum", "Chinese small dishes", "chinese"),
    ("xiaolongbao", "soup dumplings", "chinese"),
    ("baozi", "steamed buns", "chinese"),
    ("char siu", "Chinese BBQ pork", "chinese"),
    ("congee", "rice porridge", "chinese"),
    ("mapo tofu", "Sichuan tofu dish", "chinese"),
    ("kung pao chicken", "Sichuan dish", "chinese"),
    ("Sichuan", "Chinese region", "chinese"),
    ("Szechuan", "Chinese region", "chinese"),
    ("hoisin", "Chinese sauce", "chinese"),
    ("Shaoxing wine", "Chinese cooking wine", "chinese"),
    # Middle Eastern
    ("hummus", "chickpea spread", "middle_eastern"),
    ("falafel", "fried chickpea balls", "middle_eastern"),
    ("shawarma", "spit-roasted meat", "middle_eastern"),
    ("kebab", "skewered meat", "middle_eastern"),
    ("kofta", "ground meat", "middle_eastern"),
    ("dolma", "stuffed grape leaves", "middle_eastern"),
    ("tabbouleh", "parsley-bulgur salad", "middle_eastern"),
    ("baba ghanoush", "eggplant dip", "middle_eastern"),
    ("baba ganoush", "eggplant dip alternate spelling", "middle_eastern"),
    ("tahini", "sesame paste", "middle_eastern"),
    ("za'atar", "Middle Eastern spice", "middle_eastern"),
    ("sumac", "tart spice", "middle_eastern"),
    ("baklava", "sweet pastry", "middle_eastern"),
    ("kanafeh", "cheese pastry", "middle_eastern"),
    ("manakeesh", "Middle Eastern flatbread", "middle_eastern"),
    # French
    ("croissant", "French pastry", "french"),
    ("baguette", "French bread", "french"),
    ("pain au chocolat", "chocolate pastry", "french"),
    ("brioche", "rich French bread", "french"),
    ("ratatouille", "French vegetable stew", "french"),
    ("bouillabaisse", "French fish stew", "french"),
    ("coq au vin", "wine-braised chicken", "french"),
    ("cassoulet", "French slow-cooked stew", "french"),
    ("crêpe", "French thin pancake", "french"),
    ("crème brûlée", "burnt cream dessert", "french"),
    ("crème fraîche", "soured cream", "french"),
    ("foie gras", "duck/goose liver", "french"),
    ("escargot", "snails", "french"),
    ("hors d'oeuvre", "appetizer", "french"),
    ("amuse-bouche", "small bite", "french"),
    ("mille-feuille", "layered pastry", "french"),
    ("pain perdu", "French toast", "french"),
    ("Béarnaise", "egg butter sauce", "french"),
    ("Hollandaise", "egg butter sauce", "french"),
    ("Bordelaise", "red wine sauce", "french"),
    ("Provençal", "Provence-style", "french"),
    # Spanish / Latin
    ("paella", "Spanish rice dish", "spanish"),
    ("tapas", "Spanish small plates", "spanish"),
    ("jamón", "Spanish ham", "spanish"),
    ("Jamón Ibérico", "Iberian ham", "spanish"),
    ("Manchego", "Spanish sheep cheese", "spanish"),
    ("chorizo", "Spanish sausage", "spanish"),
    ("gazpacho", "cold Spanish soup", "spanish"),
    ("ceviche", "raw seafood dish", "latin"),
    ("empanada", "stuffed pastry", "latin"),
    ("arepa", "South American flatbread", "latin"),
    ("tamale", "corn dough dish", "latin"),
    ("mole", "Mexican sauce", "latin"),
    ("guacamole", "avocado dip", "latin"),
    ("birria", "Mexican stew", "latin"),
    ("barbacoa", "slow-cooked meat", "latin"),
    ("carnitas", "braised pork", "latin"),
    ("al pastor", "shawarma-style pork", "latin"),
    ("pozole", "Mexican stew", "latin"),
    ("Oaxaca", "Mexican region (cheese, mole)", "latin"),
    ("Oaxacan", "from Oaxaca", "latin"),
    ("tres leches", "three milks cake", "latin"),
    ("dulce de leche", "milk caramel", "latin"),
    ("alfajor", "South American cookie", "latin"),
    ("churro", "fried dough pastry", "latin"),
    # Brand names
    ("Cheerios", "cereal brand", "brand"),
    ("Frosted Flakes", "cereal brand", "brand"),
    ("Lucky Charms", "cereal brand", "brand"),
    ("Cap'n Crunch", "cereal brand", "brand"),
    ("Coca-Cola", "soft drink brand", "brand"),
    ("Pepsi", "soft drink brand", "brand"),
    ("Sprite", "soft drink", "brand"),
    ("Dr Pepper", "soft drink", "brand"),
    ("Mountain Dew", "soft drink", "brand"),
    ("Tim Hortons", "Canadian coffee chain", "brand"),
    ("Starbucks", "coffee chain", "brand"),
    ("Dunkin'", "coffee/donut chain", "brand"),
    ("Chick-fil-A", "fast food chain", "brand"),
    ("In-N-Out", "burger chain", "brand"),
    ("Trader Joe's", "grocery chain", "brand"),
    ("Whole Foods", "grocery chain", "brand"),
    ("Costco", "warehouse club", "brand"),
    ("Aldi", "grocery chain", "brand"),
    ("Lidl", "grocery chain", "brand"),
    ("Kraft", "food company", "brand"),
    ("Kellogg's", "food company", "brand"),
    ("General Mills", "food company", "brand"),
    ("Heinz", "food company", "brand"),
    ("Hershey's", "chocolate brand", "brand"),
    ("Cadbury", "chocolate brand", "brand"),
    ("Lindt", "chocolate brand", "brand"),
    ("Ghirardelli", "chocolate brand", "brand"),
    ("Häagen-Dazs", "ice cream brand", "brand"),
    ("Ben & Jerry's", "ice cream brand", "brand"),
    # Diet / dietary
    ("keto", "ketogenic diet", "diet"),
    ("paleo", "Paleolithic diet", "diet"),
    ("vegan", "no animal products", "diet"),
    ("vegetarian", "no meat", "diet"),
    ("pescatarian", "fish only meat", "diet"),
    ("flexitarian", "mostly plant", "diet"),
    ("FODMAP", "fermentable carbs", "diet"),
    ("gluten-free", "no wheat protein", "diet"),
    ("kosher", "Jewish dietary law", "diet"),
    ("halal", "Islamic dietary law", "diet"),
]


def iter_terms() -> Iterable[RawTerm]:
    seen: set[str] = set()
    for canonical, gloss, subcat in _TERMS:
        key = canonical.lower()
        if key in seen:
            continue
        seen.add(key)
        score = 0.65
        yield RawTerm(
            term=canonical,
            canonical_form=canonical,
            category="cooking",
            subcategory=subcat,
            sounds_like=_PRONUNCIATIONS.get(canonical, []),
            context_blurb=gloss[:140],
            popularity_score=score,
            source="Curated cooking / food terms",
        )
    logger.info("Cooking / food: %d yielded", len(seen))


name = "Cooking / Food"
category = "cooking"
