"""Curated medical / clinical terms.

Top-N drug names + conditions + procedures + anatomy that physicians
actually say. The full MeSH / RxNorm / ICD-10 datasets remain on the
TODO list (parser modules); this curated set ensures Whisper handles
the high-frequency clinical vocabulary correctly out of the box without
waiting for the full mass-dataset extraction pipelines.
"""

from __future__ import annotations

import logging
from typing import Iterable

from ..pronunciation import derive_acronym_pronunciations
from ..types import RawTerm

logger = logging.getLogger(__name__)


_TERMS: list[tuple[str, str, str]] = [
    # Top drug brand + generic names commonly mistranscribed
    ("Lipitor", "atorvastatin (brand)", "drug_brand"),
    ("atorvastatin", "statin generic name", "drug_generic"),
    ("Eliquis", "apixaban (brand)", "drug_brand"),
    ("apixaban", "anticoagulant generic", "drug_generic"),
    ("Xarelto", "rivaroxaban (brand)", "drug_brand"),
    ("rivaroxaban", "anticoagulant generic", "drug_generic"),
    ("Plavix", "clopidogrel (brand)", "drug_brand"),
    ("clopidogrel", "antiplatelet generic", "drug_generic"),
    ("Crestor", "rosuvastatin (brand)", "drug_brand"),
    ("rosuvastatin", "statin generic", "drug_generic"),
    ("Synthroid", "levothyroxine (brand)", "drug_brand"),
    ("levothyroxine", "thyroid hormone generic", "drug_generic"),
    ("Lasix", "furosemide (brand)", "drug_brand"),
    ("furosemide", "diuretic generic", "drug_generic"),
    ("Cymbalta", "duloxetine (brand)", "drug_brand"),
    ("duloxetine", "SNRI generic", "drug_generic"),
    ("Lyrica", "pregabalin (brand)", "drug_brand"),
    ("pregabalin", "anticonvulsant generic", "drug_generic"),
    ("Lexapro", "escitalopram (brand)", "drug_brand"),
    ("escitalopram", "SSRI generic", "drug_generic"),
    ("Zoloft", "sertraline (brand)", "drug_brand"),
    ("sertraline", "SSRI generic", "drug_generic"),
    ("Prozac", "fluoxetine (brand)", "drug_brand"),
    ("fluoxetine", "SSRI generic", "drug_generic"),
    ("Wellbutrin", "bupropion (brand)", "drug_brand"),
    ("bupropion", "atypical antidepressant", "drug_generic"),
    ("Effexor", "venlafaxine (brand)", "drug_brand"),
    ("venlafaxine", "SNRI generic", "drug_generic"),
    ("Adderall", "amphetamine/dextroamphetamine (brand)", "drug_brand"),
    ("Vyvanse", "lisdexamfetamine (brand)", "drug_brand"),
    ("Ritalin", "methylphenidate (brand)", "drug_brand"),
    ("Concerta", "methylphenidate ER (brand)", "drug_brand"),
    ("Ozempic", "semaglutide (brand)", "drug_brand"),
    ("semaglutide", "GLP-1 agonist generic", "drug_generic"),
    ("Wegovy", "semaglutide for weight loss", "drug_brand"),
    ("Mounjaro", "tirzepatide (brand)", "drug_brand"),
    ("tirzepatide", "GLP-1/GIP agonist generic", "drug_generic"),
    ("Zepbound", "tirzepatide for weight loss", "drug_brand"),
    ("Trulicity", "dulaglutide (brand)", "drug_brand"),
    ("dulaglutide", "GLP-1 agonist generic", "drug_generic"),
    ("metformin", "biguanide for diabetes", "drug_generic"),
    ("Glucophage", "metformin (brand)", "drug_brand"),
    ("Jardiance", "empagliflozin (brand)", "drug_brand"),
    ("empagliflozin", "SGLT2 inhibitor generic", "drug_generic"),
    ("Farxiga", "dapagliflozin (brand)", "drug_brand"),
    ("Humira", "adalimumab (brand)", "drug_brand"),
    ("adalimumab", "TNF inhibitor generic", "drug_generic"),
    ("Enbrel", "etanercept (brand)", "drug_brand"),
    ("Remicade", "infliximab (brand)", "drug_brand"),
    ("Stelara", "ustekinumab (brand)", "drug_brand"),
    ("Skyrizi", "risankizumab (brand)", "drug_brand"),
    ("Botox", "onabotulinumtoxinA (brand)", "drug_brand"),
    ("onabotulinumtoxinA", "botulinum toxin A", "drug_generic"),
    ("ibuprofen", "NSAID", "drug_generic"),
    ("acetaminophen", "analgesic generic", "drug_generic"),
    ("paracetamol", "acetaminophen UK name", "drug_generic"),
    ("Tylenol", "acetaminophen (brand)", "drug_brand"),
    ("Advil", "ibuprofen (brand)", "drug_brand"),
    ("Motrin", "ibuprofen (brand)", "drug_brand"),
    ("Aleve", "naproxen (brand)", "drug_brand"),
    ("naproxen", "NSAID generic", "drug_generic"),
    ("aspirin", "acetylsalicylic acid", "drug_generic"),
    # Top conditions
    ("hypertension", "high blood pressure", "condition"),
    ("hyperlipidemia", "high cholesterol", "condition"),
    ("hypercholesterolemia", "high blood cholesterol", "condition"),
    ("diabetes mellitus", "diabetes", "condition"),
    ("type 2 diabetes", "T2DM", "condition"),
    ("type 1 diabetes", "T1DM", "condition"),
    ("hypothyroidism", "underactive thyroid", "condition"),
    ("hyperthyroidism", "overactive thyroid", "condition"),
    ("hashimoto thyroiditis", "autoimmune thyroid disease", "condition"),
    ("graves disease", "autoimmune hyperthyroid", "condition"),
    ("myocardial infarction", "heart attack", "condition"),
    ("congestive heart failure", "CHF", "condition"),
    ("atrial fibrillation", "AFib", "condition"),
    ("AFib", "atrial fibrillation", "condition"),
    ("CHF", "congestive heart failure", "condition"),
    ("COPD", "chronic obstructive pulmonary disease", "condition"),
    ("asthma", "chronic respiratory condition", "condition"),
    ("pneumonia", "lung infection", "condition"),
    ("bronchitis", "bronchial inflammation", "condition"),
    ("influenza", "flu", "condition"),
    ("COVID-19", "coronavirus disease 2019", "condition"),
    ("Alzheimer disease", "neurodegenerative disorder", "condition"),
    ("Parkinson disease", "movement disorder", "condition"),
    ("multiple sclerosis", "MS", "condition"),
    ("ALS", "amyotrophic lateral sclerosis", "condition"),
    ("Crohn disease", "IBD", "condition"),
    ("ulcerative colitis", "IBD", "condition"),
    ("rheumatoid arthritis", "RA", "condition"),
    ("osteoarthritis", "OA", "condition"),
    ("fibromyalgia", "chronic pain syndrome", "condition"),
    ("chronic fatigue syndrome", "CFS", "condition"),
    ("ME/CFS", "myalgic encephalomyelitis", "condition"),
    ("anxiety disorder", "GAD", "condition"),
    ("major depressive disorder", "MDD", "condition"),
    ("bipolar disorder", "bipolar", "condition"),
    ("schizophrenia", "psychotic disorder", "condition"),
    ("PTSD", "post-traumatic stress disorder", "condition"),
    ("ADHD", "attention deficit hyperactivity disorder", "condition"),
    ("ASD", "autism spectrum disorder", "condition"),
    ("OCD", "obsessive-compulsive disorder", "condition"),
    ("HIV", "human immunodeficiency virus", "condition"),
    ("AIDS", "acquired immunodeficiency syndrome", "condition"),
    ("hepatitis C", "HCV", "condition"),
    ("hepatitis B", "HBV", "condition"),
    ("cirrhosis", "liver scarring", "condition"),
    ("CKD", "chronic kidney disease", "condition"),
    ("ESRD", "end-stage renal disease", "condition"),
    # Top procedures
    ("colonoscopy", "colon endoscopy", "procedure"),
    ("endoscopy", "internal scope", "procedure"),
    ("EGD", "esophagogastroduodenoscopy", "procedure"),
    ("ERCP", "endoscopic retrograde cholangiopancreatography", "procedure"),
    ("MRI", "magnetic resonance imaging", "procedure"),
    ("CT scan", "computed tomography", "procedure"),
    ("PET scan", "positron emission tomography", "procedure"),
    ("X-ray", "radiograph", "procedure"),
    ("ultrasound", "sonography", "procedure"),
    ("echocardiogram", "heart ultrasound", "procedure"),
    ("EKG", "electrocardiogram", "procedure"),
    ("ECG", "electrocardiogram", "procedure"),
    ("EEG", "electroencephalogram", "procedure"),
    ("biopsy", "tissue sampling", "procedure"),
    ("appendectomy", "appendix removal", "procedure"),
    ("cholecystectomy", "gallbladder removal", "procedure"),
    ("hysterectomy", "uterus removal", "procedure"),
    ("mastectomy", "breast removal", "procedure"),
    ("lumpectomy", "tumor removal", "procedure"),
    ("CABG", "coronary artery bypass grafting", "procedure"),
    ("PCI", "percutaneous coronary intervention", "procedure"),
    ("angioplasty", "vessel widening", "procedure"),
    ("dialysis", "renal replacement therapy", "procedure"),
    ("chemotherapy", "cancer drug therapy", "procedure"),
    ("radiotherapy", "radiation therapy", "procedure"),
    ("immunotherapy", "immune-based therapy", "procedure"),
    # Anatomy commonly mistranscribed
    ("aorta", "main artery", "anatomy"),
    ("pulmonary", "lung-related", "anatomy"),
    ("cerebellum", "back of brain", "anatomy"),
    ("hippocampus", "memory structure", "anatomy"),
    ("amygdala", "fear processing", "anatomy"),
    ("hypothalamus", "below thalamus", "anatomy"),
    ("pituitary", "master endocrine gland", "anatomy"),
    ("thyroid", "neck endocrine gland", "anatomy"),
    ("pancreas", "abdominal gland", "anatomy"),
    ("duodenum", "first small intestine section", "anatomy"),
    ("jejunum", "middle small intestine", "anatomy"),
    ("ileum", "last small intestine section", "anatomy"),
    ("esophagus", "swallowing tube", "anatomy"),
    ("trachea", "windpipe", "anatomy"),
    ("larynx", "voice box", "anatomy"),
    ("pharynx", "throat", "anatomy"),
    ("femur", "thighbone", "anatomy"),
    ("humerus", "upper arm bone", "anatomy"),
    ("clavicle", "collarbone", "anatomy"),
    ("scapula", "shoulder blade", "anatomy"),
    # Specialties
    ("cardiology", "heart medicine", "specialty"),
    ("oncology", "cancer medicine", "specialty"),
    ("neurology", "nervous system medicine", "specialty"),
    ("endocrinology", "hormone medicine", "specialty"),
    ("gastroenterology", "GI medicine", "specialty"),
    ("nephrology", "kidney medicine", "specialty"),
    ("pulmonology", "lung medicine", "specialty"),
    ("rheumatology", "joints/autoimmune medicine", "specialty"),
    ("dermatology", "skin medicine", "specialty"),
    ("ophthalmology", "eye medicine", "specialty"),
    ("otolaryngology", "ENT medicine", "specialty"),
    ("orthopedics", "musculoskeletal surgery", "specialty"),
    ("anesthesiology", "anesthesia medicine", "specialty"),
    ("radiology", "imaging medicine", "specialty"),
    ("pathology", "diagnostic medicine", "specialty"),
    ("psychiatry", "mental health medicine", "specialty"),
    ("pediatrics", "child medicine", "specialty"),
    ("obstetrics", "pregnancy medicine", "specialty"),
    ("gynecology", "women's reproductive medicine", "specialty"),
]


# Pronunciation hints for medical terms. Drug names especially are
# pronunciation traps — Whisper hears the audio and can't decide
# between brand vs. generic, or between similar-sounding compounds.
# These hints are how the spoken form usually gets typed:
_MED_PRONUNCIATIONS: dict[str, list[str]] = {
    # Drugs — generic
    "atorvastatin": ["uh tor vah stat in", "a-tor-va-stat-in"],
    "rosuvastatin": ["ros oo vah stat in", "ros-oo-va-stat-in"],
    "apixaban": ["uh pix uh ban", "a-pix-uh-ban"],
    "rivaroxaban": ["riv ar ox uh ban"],
    "clopidogrel": ["kloh pid uh grel"],
    "levothyroxine": ["lee voh thigh rox een"],
    "furosemide": ["fyu roh suh mide"],
    "duloxetine": ["du lox uh teen"],
    "pregabalin": ["preh gab uh lin"],
    "escitalopram": ["es sit al uh pram"],
    "sertraline": ["sir truh leen"],
    "fluoxetine": ["floo ox uh teen"],
    "bupropion": ["byu proh pee on"],
    "venlafaxine": ["ven luh fax een"],
    "semaglutide": ["sem uh gloo tide"],
    "tirzepatide": ["tirz ep uh tide"],
    "dulaglutide": ["du la gloo tide"],
    "metformin": ["met for min"],
    "empagliflozin": ["em puh gluh floh zin"],
    "dapagliflozin": ["dap uh gluh floh zin"],
    "adalimumab": ["a duh lim oo mab"],
    "etanercept": ["eh tan er sept"],
    "infliximab": ["in flix ih mab"],
    "ustekinumab": ["yoo steh kin oo mab"],
    "risankizumab": ["riss an kiz oo mab"],
    "ibuprofen": ["eye byu proh fen"],
    "acetaminophen": ["uh see tuh min uh fen"],
    "naproxen": ["nuh prox en"],
    # Drugs — brand
    "Lipitor": ["lip ih tor"],
    "Eliquis": ["el ih kwis"],
    "Xarelto": ["zah rel toh"],
    "Plavix": ["play vix"],
    "Crestor": ["kres tor"],
    "Synthroid": ["sin throid"],
    "Lasix": ["lay six"],
    "Cymbalta": ["sim bal tuh"],
    "Lyrica": ["lear ih kuh"],
    "Lexapro": ["lex uh pro"],
    "Zoloft": ["zoh loft"],
    "Prozac": ["proh zak"],
    "Wellbutrin": ["well byu trin"],
    "Effexor": ["ef ex or"],
    "Adderall": ["ad er all"],
    "Vyvanse": ["vy vance"],
    "Ritalin": ["rit uh lin"],
    "Concerta": ["kun sair tuh"],
    "Ozempic": ["oh zem pik"],
    "Wegovy": ["weh goh vee"],
    "Mounjaro": ["mown jar oh"],
    "Zepbound": ["zep bownd"],
    "Trulicity": ["troo liss ih tee"],
    "Glucophage": ["gloo koh fage"],
    "Jardiance": ["jar dee ans"],
    "Farxiga": ["far zee guh"],
    "Humira": ["hyu meer uh"],
    "Enbrel": ["en brel"],
    "Remicade": ["rem ih kade"],
    "Stelara": ["stuh lar uh"],
    "Skyrizi": ["sky rye zee"],
    "Tylenol": ["tie len ol"],
    # Conditions
    "myocardial infarction": ["my oh kar dee ul in fark shun"],
    "atrial fibrillation": ["ay tree ul fib ruh lay shun", "a fib"],
    "AFib": ["ay fib"],
    "hypothyroidism": ["hi poh thigh roi diz um"],
    "hyperthyroidism": ["hi per thigh roi diz um"],
    "hashimoto thyroiditis": ["hah shee moh toh thigh roi die tis"],
    "schizophrenia": ["skit suh free nee uh"],
    "fibromyalgia": ["fye broh my al jee uh"],
    "rheumatoid arthritis": ["roo muh toid ar thrye tis"],
    "osteoarthritis": ["os tee oh ar thrye tis"],
    # Procedures
    "colonoscopy": ["koh luh nos koh pee"],
    "endoscopy": ["en dos koh pee"],
    "esophagogastroduodenoscopy": ["eh sof uh go gas troh dyu od en os koh pee"],
    "EGD": ["ee gee dee"],
    "ERCP": ["ee ar see pee"],
    "MRI": ["em ar eye"],
    "CT scan": ["see tee scan"],
    "PET scan": ["pet scan"],
    "EKG": ["ee kay gee"],
    "ECG": ["ee see gee"],
    "EEG": ["ee ee gee"],
    "appendectomy": ["uh pen dek tuh mee"],
    "cholecystectomy": ["koh leh sis tek tuh mee"],
    "hysterectomy": ["his ter ek tuh mee"],
    "mastectomy": ["mass tek tuh mee"],
    "lumpectomy": ["lump ek tuh mee"],
    "CABG": ["cabbage"],  # Coronary Artery Bypass Graft is universally "cabbage"
    "PCI": ["pee see eye"],
    # Anatomy
    "aorta": ["ay or tuh"],
    "cerebellum": ["sair uh bell um"],
    "hippocampus": ["hip oh kam pus"],
    "amygdala": ["uh mig duh luh"],
    "hypothalamus": ["hi poh thal uh mus"],
    "esophagus": ["eh sof uh gus"],
    "trachea": ["tray kee uh"],
    "larynx": ["lar inks"],
    "pharynx": ["fair inks"],
    "duodenum": ["dyu uh dee num", "dyu od en um"],
    "jejunum": ["jeh jew num"],
    "ileum": ["ill ee um"],
    "femur": ["fee mer"],
    "humerus": ["hyu mer us"],
    "clavicle": ["klav ih kul"],
    "scapula": ["skap yu luh"],
    # Specialties
    "cardiology": ["kar dee ol oh jee"],
    "oncology": ["on kol oh jee"],
    "neurology": ["nyu rol oh jee"],
    "endocrinology": ["en doh krin ol oh jee"],
    "gastroenterology": ["gas troh en ter ol oh jee"],
    "nephrology": ["neh frol oh jee"],
    "pulmonology": ["pul mon ol oh jee"],
    "rheumatology": ["roo muh tol oh jee"],
    "dermatology": ["der muh tol oh jee"],
    "ophthalmology": ["off thal mol oh jee"],
    "otolaryngology": ["oh toh lair in gol oh jee"],
    "orthopedics": ["or thoh pee diks"],
    "anesthesiology": ["an es thee zee ol oh jee"],
    "radiology": ["ray dee ol oh jee"],
    "pathology": ["puh thol oh jee"],
    "psychiatry": ["sye kye uh tree"],
    "obstetrics": ["ob stet riks"],
    "gynecology": ["gye nuh kol oh jee", "jin uh kol oh jee"],
}


def iter_terms() -> Iterable[RawTerm]:
    seen: set[str] = set()
    for canonical, gloss, subcat in _TERMS:
        key = canonical.lower()
        if key in seen:
            continue
        seen.add(key)
        score = 0.7 if subcat in {"drug_brand", "condition", "specialty"} else 0.55
        # Prefer explicit pronunciation when curated; otherwise leave
        # blank (Whisper handles common medical terms fine without
        # phonetic hints — only the hard cases are in _MED_PRONUNCIATIONS).
        explicit = _MED_PRONUNCIATIONS.get(canonical, [])
        if canonical.isupper() and len(canonical) <= 6:
            sounds_like = derive_acronym_pronunciations(canonical, extra_hints=explicit)
        else:
            sounds_like = list(explicit)
        yield RawTerm(
            term=canonical,
            canonical_form=canonical,
            category="medical",
            subcategory=subcat,
            sounds_like=sounds_like,
            context_blurb=gloss[:140],
            popularity_score=score,
            source="Curated medical terms",
        )
    logger.info("Medical (curated): %d terms yielded", len(seen))


name = "Medical Terms (Curated)"
category = "medical"
