"""Curated medical / clinical terms.

Top-N drug names + conditions + procedures + anatomy that physicians
actually say. The full MeSH / RxNorm / ICD-10 datasets remain on the
TODO list (parser modules); this curated set ensures Whisper handles
the high-frequency clinical vocabulary correctly out of the box without
waiting for the full mass-dataset extraction pipelines.
"""

from __future__ import annotations

import logging
from typing import Iterable

from ..pronunciation import derive_acronym_pronunciations
from ..types import RawTerm

logger = logging.getLogger(__name__)


_TERMS: list[tuple[str, str, str]] = [
    # Top drug brand + generic names commonly mistranscribed
    ("Lipitor", "atorvastatin (brand)", "drug_brand"),
    ("atorvastatin", "statin generic name", "drug_generic"),
    ("Eliquis", "apixaban (brand)", "drug_brand"),
    ("apixaban", "anticoagulant generic", "drug_generic"),
    ("Xarelto", "rivaroxaban (brand)", "drug_brand"),
    ("rivaroxaban", "anticoagulant generic", "drug_generic"),
    ("Plavix", "clopidogrel (brand)", "drug_brand"),
    ("clopidogrel", "antiplatelet generic", "drug_generic"),
    ("Crestor", "rosuvastatin (brand)", "drug_brand"),
    ("rosuvastatin", "statin generic", "drug_generic"),
    ("Synthroid", "levothyroxine (brand)", "drug_brand"),
    ("levothyroxine", "thyroid hormone generic", "drug_generic"),
    ("Lasix", "furosemide (brand)", "drug_brand"),
    ("furosemide", "diuretic generic", "drug_generic"),
    ("Cymbalta", "duloxetine (brand)", "drug_brand"),
    ("duloxetine", "SNRI generic", "drug_generic"),
    ("Lyrica", "pregabalin (brand)", "drug_brand"),
    ("pregabalin", "anticonvulsant generic", "drug_generic"),
    ("Lexapro", "escitalopram (brand)", "drug_brand"),
    ("escitalopram", "SSRI generic", "drug_generic"),
    ("Zoloft", "sertraline (brand)", "drug_brand"),
    ("sertraline", "SSRI generic", "drug_generic"),
    ("Prozac", "fluoxetine (brand)", "drug_brand"),
    ("fluoxetine", "SSRI generic", "drug_generic"),
    ("Wellbutrin", "bupropion (brand)", "drug_brand"),
    ("bupropion", "atypical antidepressant", "drug_generic"),
    ("Effexor", "venlafaxine (brand)", "drug_brand"),
    ("venlafaxine", "SNRI generic", "drug_generic"),
    ("Adderall", "amphetamine/dextroamphetamine (brand)", "drug_brand"),
    ("Vyvanse", "lisdexamfetamine (brand)", "drug_brand"),
    ("Ritalin", "methylphenidate (brand)", "drug_brand"),
    ("Concerta", "methylphenidate ER (brand)", "drug_brand"),
    ("Ozempic", "semaglutide (brand)", "drug_brand"),
    ("semaglutide", "GLP-1 agonist generic", "drug_generic"),
    ("Wegovy", "semaglutide for weight loss", "drug_brand"),
    ("Mounjaro", "tirzepatide (brand)", "drug_brand"),
    ("tirzepatide", "GLP-1/GIP agonist generic", "drug_generic"),
    ("Zepbound", "tirzepatide for weight loss", "drug_brand"),
    ("Trulicity", "dulaglutide (brand)", "drug_brand"),
    ("dulaglutide", "GLP-1 agonist generic", "drug_generic"),
    ("metformin", "biguanide for diabetes", "drug_generic"),
    ("Glucophage", "metformin (brand)", "drug_brand"),
    ("Jardiance", "empagliflozin (brand)", "drug_brand"),
    ("empagliflozin", "SGLT2 inhibitor generic", "drug_generic"),
    ("Farxiga", "dapagliflozin (brand)", "drug_brand"),
    ("Humira", "adalimumab (brand)", "drug_brand"),
    ("adalimumab", "TNF inhibitor generic", "drug_generic"),
    ("Enbrel", "etanercept (brand)", "drug_brand"),
    ("Remicade", "infliximab (brand)", "drug_brand"),
    ("Stelara", "ustekinumab (brand)", "drug_brand"),
    ("Skyrizi", "risankizumab (brand)", "drug_brand"),
    ("Botox", "onabotulinumtoxinA (brand)", "drug_brand"),
    ("onabotulinumtoxinA", "botulinum toxin A", "drug_generic"),
    ("ibuprofen", "NSAID", "drug_generic"),
    ("acetaminophen", "analgesic generic", "drug_generic"),
    ("paracetamol", "acetaminophen UK name", "drug_generic"),
    ("Tylenol", "acetaminophen (brand)", "drug_brand"),
    ("Advil", "ibuprofen (brand)", "drug_brand"),
    ("Motrin", "ibuprofen (brand)", "drug_brand"),
    ("Aleve", "naproxen (brand)", "drug_brand"),
    ("naproxen", "NSAID generic", "drug_generic"),
    ("aspirin", "acetylsalicylic acid", "drug_generic"),
    # Top conditions
    ("hypertension", "high blood pressure", "condition"),
    ("hyperlipidemia", "high cholesterol", "condition"),
    ("hypercholesterolemia", "high blood cholesterol", "condition"),
    ("diabetes mellitus", "diabetes", "condition"),
    ("type 2 diabetes", "T2DM", "condition"),
    ("type 1 diabetes", "T1DM", "condition"),
    ("hypothyroidism", "underactive thyroid", "condition"),
    ("hyperthyroidism", "overactive thyroid", "condition"),
    ("hashimoto thyroiditis", "autoimmune thyroid disease", "condition"),
    ("graves disease", "autoimmune hyperthyroid", "condition"),
    ("myocardial infarction", "heart attack", "condition"),
    ("congestive heart failure", "CHF", "condition"),
    ("atrial fibrillation", "AFib", "condition"),
    ("AFib", "atrial fibrillation", "condition"),
    ("CHF", "congestive heart failure", "condition"),
    ("COPD", "chronic obstructive pulmonary disease", "condition"),
    ("asthma", "chronic respiratory condition", "condition"),
    ("pneumonia", "lung infection", "condition"),
    ("bronchitis", "bronchial inflammation", "condition"),
    ("influenza", "flu", "condition"),
    ("COVID-19", "coronavirus disease 2019", "condition"),
    ("Alzheimer disease", "neurodegenerative disorder", "condition"),
    ("Parkinson disease", "movement disorder", "condition"),
    ("multiple sclerosis", "MS", "condition"),
    ("ALS", "amyotrophic lateral sclerosis", "condition"),
    ("Crohn disease", "IBD", "condition"),
    ("ulcerative colitis", "IBD", "condition"),
    ("rheumatoid arthritis", "RA", "condition"),
    ("osteoarthritis", "OA", "condition"),
    ("fibromyalgia", "chronic pain syndrome", "condition"),
    ("chronic fatigue syndrome", "CFS", "condition"),
    ("ME/CFS", "myalgic encephalomyelitis", "condition"),
    ("anxiety disorder", "GAD", "condition"),
    ("major depressive disorder", "MDD", "condition"),
    ("bipolar disorder", "bipolar", "condition"),
    ("schizophrenia", "psychotic disorder", "condition"),
    ("PTSD", "post-traumatic stress disorder", "condition"),
    ("ADHD", "attention deficit hyperactivity disorder", "condition"),
    ("ASD", "autism spectrum disorder", "condition"),
    ("OCD", "obsessive-compulsive disorder", "condition"),
    ("HIV", "human immunodeficiency virus", "condition"),
    ("AIDS", "acquired immunodeficiency syndrome", "condition"),
    ("hepatitis C", "HCV", "condition"),
    ("hepatitis B", "HBV", "condition"),
    ("cirrhosis", "liver scarring", "condition"),
    ("CKD", "chronic kidney disease", "condition"),
    ("ESRD", "end-stage renal disease", "condition"),
    # Top procedures
    ("colonoscopy", "colon endoscopy", "procedure"),
    ("endoscopy", "internal scope", "procedure"),
    ("EGD", "esophagogastroduodenoscopy", "procedure"),
    ("ERCP", "endoscopic retrograde cholangiopancreatography", "procedure"),
    ("MRI", "magnetic resonance imaging", "procedure"),
    ("CT scan", "computed tomography", "procedure"),
    ("PET scan", "positron emission tomography", "procedure"),
    ("X-ray", "radiograph", "procedure"),
    ("ultrasound", "sonography", "procedure"),
    ("echocardiogram", "heart ultrasound", "procedure"),
    ("EKG", "electrocardiogram", "procedure"),
    ("ECG", "electrocardiogram", "procedure"),
    ("EEG", "electroencephalogram", "procedure"),
    ("biopsy", "tissue sampling", "procedure"),
    ("appendectomy", "appendix removal", "procedure"),
    ("cholecystectomy", "gallbladder removal", "procedure"),
    ("hysterectomy", "uterus removal", "procedure"),
    ("mastectomy", "breast removal", "procedure"),
    ("lumpectomy", "tumor removal", "procedure"),
    ("CABG", "coronary artery bypass grafting", "procedure"),
    ("PCI", "percutaneous coronary intervention", "procedure"),
    ("angioplasty", "vessel widening", "procedure"),
    ("dialysis", "renal replacement therapy", "procedure"),
    ("chemotherapy", "cancer drug therapy", "procedure"),
    ("radiotherapy", "radiation therapy", "procedure"),
    ("immunotherapy", "immune-based therapy", "procedure"),
    # Anatomy commonly mistranscribed
    ("aorta", "main artery", "anatomy"),
    ("pulmonary", "lung-related", "anatomy"),
    ("cerebellum", "back of brain", "anatomy"),
    ("hippocampus", "memory structure", "anatomy"),
    ("amygdala", "fear processing", "anatomy"),
    ("hypothalamus", "below thalamus", "anatomy"),
    ("pituitary", "master endocrine gland", "anatomy"),
    ("thyroid", "neck endocrine gland", "anatomy"),
    ("pancreas", "abdominal gland", "anatomy"),
    ("duodenum", "first small intestine section", "anatomy"),
    ("jejunum", "middle small intestine", "anatomy"),
    ("ileum", "last small intestine section", "anatomy"),
    ("esophagus", "swallowing tube", "anatomy"),
    ("trachea", "windpipe", "anatomy"),
    ("larynx", "voice box", "anatomy"),
    ("pharynx", "throat", "anatomy"),
    ("femur", "thighbone", "anatomy"),
    ("humerus", "upper arm bone", "anatomy"),
    ("clavicle", "collarbone", "anatomy"),
    ("scapula", "shoulder blade", "anatomy"),
    # Specialties
    ("cardiology", "heart medicine", "specialty"),
    ("oncology", "cancer medicine", "specialty"),
    ("neurology", "nervous system medicine", "specialty"),
    ("endocrinology", "hormone medicine", "specialty"),
    ("gastroenterology", "GI medicine", "specialty"),
    ("nephrology", "kidney medicine", "specialty"),
    ("pulmonology", "lung medicine", "specialty"),
    ("rheumatology", "joints/autoimmune medicine", "specialty"),
    ("dermatology", "skin medicine", "specialty"),
    ("ophthalmology", "eye medicine", "specialty"),
    ("otolaryngology", "ENT medicine", "specialty"),
    ("orthopedics", "musculoskeletal surgery", "specialty"),
    ("anesthesiology", "anesthesia medicine", "specialty"),
    ("radiology", "imaging medicine", "specialty"),
    ("pathology", "diagnostic medicine", "specialty"),
    ("psychiatry", "mental health medicine", "specialty"),
    ("pediatrics", "child medicine", "specialty"),
    ("obstetrics", "pregnancy medicine", "specialty"),
    ("gynecology", "women's reproductive medicine", "specialty"),
    # ── Medical acronyms commonly mistranscribed ────────────────────
    # These are uppercase, frequently spoken, and Whisper's phonetic
    # confusion produces real-English-sounding pseudo-words. Each
    # carries explicit sounds_like in _MED_PRONUNCIATIONS below for
    # the misread shapes.
    ("HIPAA", "Health Insurance Portability and Accountability Act", "med_acronym"),
    ("PHI", "Protected Health Information", "med_acronym"),
    ("EHR", "Electronic Health Record", "med_acronym"),
    ("EMR", "Electronic Medical Record", "med_acronym"),
    ("PHR", "Personal Health Record", "med_acronym"),
    ("HMO", "Health Maintenance Organization", "med_acronym"),
    ("PPO", "Preferred Provider Organization", "med_acronym"),
    ("ACA", "Affordable Care Act", "med_acronym"),
    ("CMS", "Centers for Medicare and Medicaid Services", "med_acronym"),
    ("FDA", "Food and Drug Administration", "med_acronym"),
    ("CDC", "Centers for Disease Control and Prevention", "med_acronym"),
    ("WHO", "World Health Organization", "med_acronym"),
    ("NIH", "National Institutes of Health", "med_acronym"),
    ("PTSD", "Post-Traumatic Stress Disorder", "med_acronym"),
    ("ADHD", "Attention-Deficit/Hyperactivity Disorder", "med_acronym"),
    ("ADD", "Attention Deficit Disorder", "med_acronym"),
    ("OCD", "Obsessive-Compulsive Disorder", "med_acronym"),
    ("PPD", "Postpartum Depression", "med_acronym"),
    ("COPD", "Chronic Obstructive Pulmonary Disease", "med_acronym"),
    ("CHF", "Congestive Heart Failure", "med_acronym"),
    ("MI", "Myocardial Infarction (heart attack)", "med_acronym"),
    ("CVA", "Cerebrovascular Accident (stroke)", "med_acronym"),
    ("DVT", "Deep Vein Thrombosis", "med_acronym"),
    ("PE", "Pulmonary Embolism", "med_acronym"),
    ("CKD", "Chronic Kidney Disease", "med_acronym"),
    ("ESRD", "End-Stage Renal Disease", "med_acronym"),
    ("UTI", "Urinary Tract Infection", "med_acronym"),
    ("BPH", "Benign Prostatic Hyperplasia", "med_acronym"),
    ("GERD", "Gastroesophageal Reflux Disease", "med_acronym"),
    ("IBS", "Irritable Bowel Syndrome", "med_acronym"),
    ("IBD", "Inflammatory Bowel Disease", "med_acronym"),
    ("RA", "Rheumatoid Arthritis", "med_acronym"),
    ("OA", "Osteoarthritis", "med_acronym"),
    ("SLE", "Systemic Lupus Erythematosus (lupus)", "med_acronym"),
    ("MS", "Multiple Sclerosis", "med_acronym"),
    ("ALS", "Amyotrophic Lateral Sclerosis", "med_acronym"),
    ("TBI", "Traumatic Brain Injury", "med_acronym"),
    ("CT", "Computed Tomography (CT scan)", "med_acronym"),
    ("MRI", "Magnetic Resonance Imaging", "med_acronym"),
    ("PET", "Positron Emission Tomography", "med_acronym"),
    ("EKG", "Electrocardiogram", "med_acronym"),
    ("ECG", "Electrocardiogram", "med_acronym"),
    ("EEG", "Electroencephalogram", "med_acronym"),
    ("CBC", "Complete Blood Count", "med_acronym"),
    ("BMP", "Basic Metabolic Panel", "med_acronym"),
    ("CMP", "Comprehensive Metabolic Panel", "med_acronym"),
    ("PT/INR", "Prothrombin Time / International Normalized Ratio", "med_acronym"),
    ("BUN", "Blood Urea Nitrogen", "med_acronym"),
    ("HbA1c", "Hemoglobin A1c (glycated hemoglobin)", "med_acronym"),
    ("LDL", "Low-Density Lipoprotein (cholesterol)", "med_acronym"),
    ("HDL", "High-Density Lipoprotein (cholesterol)", "med_acronym"),
    ("BMI", "Body Mass Index", "med_acronym"),
    ("BP", "Blood Pressure", "med_acronym"),
    ("HR", "Heart Rate", "med_acronym"),
    ("ICU", "Intensive Care Unit", "med_acronym"),
    ("NICU", "Neonatal Intensive Care Unit", "med_acronym"),
    ("PICU", "Pediatric Intensive Care Unit", "med_acronym"),
    ("ER", "Emergency Room", "med_acronym"),
    ("ED", "Emergency Department", "med_acronym"),
    ("OR", "Operating Room", "med_acronym"),
    ("PACU", "Post-Anesthesia Care Unit", "med_acronym"),
    ("NPO", "Nothing By Mouth (nil per os)", "med_acronym"),
    ("IV", "Intravenous", "med_acronym"),
    ("IM", "Intramuscular", "med_acronym"),
    ("SubQ", "Subcutaneous (medication route)", "med_acronym"),
    ("PRN", "As needed (pro re nata)", "med_acronym"),
    ("STAT", "Immediately (statim)", "med_acronym"),
    ("SOB", "Shortness of Breath", "med_acronym"),
    ("DNR", "Do Not Resuscitate", "med_acronym"),
    ("DNI", "Do Not Intubate", "med_acronym"),
    ("CPR", "Cardiopulmonary Resuscitation", "med_acronym"),
    ("AED", "Automated External Defibrillator", "med_acronym"),
    ("BLS", "Basic Life Support", "med_acronym"),
    ("ACLS", "Advanced Cardiac Life Support", "med_acronym"),
    ("PEA", "Pulseless Electrical Activity", "med_acronym"),
    ("ROSC", "Return of Spontaneous Circulation", "med_acronym"),
]


# Pronunciation hints for medical terms. Drug names especially are
# pronunciation traps — Whisper hears the audio and can't decide
# between brand vs. generic, or between similar-sounding compounds.
# These hints are how the spoken form usually gets typed:
_MED_PRONUNCIATIONS: dict[str, list[str]] = {
    # Drugs — generic
    "atorvastatin": ["uh tor vah stat in", "a-tor-va-stat-in"],
    "rosuvastatin": ["ros oo vah stat in", "ros-oo-va-stat-in"],
    "apixaban": ["uh pix uh ban", "a-pix-uh-ban"],
    "rivaroxaban": ["riv ar ox uh ban"],
    "clopidogrel": ["kloh pid uh grel"],
    "levothyroxine": ["lee voh thigh rox een"],
    "furosemide": ["fyu roh suh mide"],
    "duloxetine": ["du lox uh teen"],
    "pregabalin": ["preh gab uh lin"],
    "escitalopram": ["es sit al uh pram"],
    "sertraline": ["sir truh leen"],
    "fluoxetine": ["floo ox uh teen"],
    "bupropion": ["byu proh pee on"],
    "venlafaxine": ["ven luh fax een"],
    "semaglutide": ["sem uh gloo tide"],
    "tirzepatide": ["tirz ep uh tide"],
    "dulaglutide": ["du la gloo tide"],
    "metformin": ["met for min"],
    "empagliflozin": ["em puh gluh floh zin"],
    "dapagliflozin": ["dap uh gluh floh zin"],
    "adalimumab": ["a duh lim oo mab"],
    "etanercept": ["eh tan er sept"],
    "infliximab": ["in flix ih mab"],
    "ustekinumab": ["yoo steh kin oo mab"],
    "risankizumab": ["riss an kiz oo mab"],
    "ibuprofen": ["eye byu proh fen"],
    "acetaminophen": ["uh see tuh min uh fen"],
    "naproxen": ["nuh prox en"],
    # Drugs — brand
    "Lipitor": ["lip ih tor"],
    "Eliquis": ["el ih kwis"],
    "Xarelto": ["zah rel toh"],
    "Plavix": ["play vix"],
    "Crestor": ["kres tor"],
    "Synthroid": ["sin throid"],
    "Lasix": ["lay six"],
    "Cymbalta": ["sim bal tuh"],
    "Lyrica": ["lear ih kuh"],
    "Lexapro": ["lex uh pro"],
    "Zoloft": ["zoh loft"],
    "Prozac": ["proh zak"],
    "Wellbutrin": ["well byu trin"],
    "Effexor": ["ef ex or"],
    "Adderall": ["ad er all"],
    "Vyvanse": ["vy vance"],
    "Ritalin": ["rit uh lin"],
    "Concerta": ["kun sair tuh"],
    "Ozempic": ["oh zem pik"],
    "Wegovy": ["weh goh vee"],
    "Mounjaro": ["mown jar oh"],
    "Zepbound": ["zep bownd"],
    "Trulicity": ["troo liss ih tee"],
    "Glucophage": ["gloo koh fage"],
    "Jardiance": ["jar dee ans"],
    "Farxiga": ["far zee guh"],
    "Humira": ["hyu meer uh"],
    "Enbrel": ["en brel"],
    "Remicade": ["rem ih kade"],
    "Stelara": ["stuh lar uh"],
    "Skyrizi": ["sky rye zee"],
    "Tylenol": ["tie len ol"],
    # Conditions
    "myocardial infarction": ["my oh kar dee ul in fark shun"],
    "atrial fibrillation": ["ay tree ul fib ruh lay shun", "a fib"],
    "AFib": ["ay fib"],
    "hypothyroidism": ["hi poh thigh roi diz um"],
    "hyperthyroidism": ["hi per thigh roi diz um"],
    "hashimoto thyroiditis": ["hah shee moh toh thigh roi die tis"],
    "schizophrenia": ["skit suh free nee uh"],
    "fibromyalgia": ["fye broh my al jee uh"],
    "rheumatoid arthritis": ["roo muh toid ar thrye tis"],
    "osteoarthritis": ["os tee oh ar thrye tis"],
    # Procedures
    "colonoscopy": ["koh luh nos koh pee"],
    "endoscopy": ["en dos koh pee"],
    "esophagogastroduodenoscopy": ["eh sof uh go gas troh dyu od en os koh pee"],
    "EGD": ["ee gee dee"],
    "ERCP": ["ee ar see pee"],
    "MRI": ["em ar eye"],
    "CT scan": ["see tee scan"],
    "PET scan": ["pet scan"],
    "EKG": ["ee kay gee"],
    "ECG": ["ee see gee"],
    "EEG": ["ee ee gee"],
    "appendectomy": ["uh pen dek tuh mee"],
    "cholecystectomy": ["koh leh sis tek tuh mee"],
    "hysterectomy": ["his ter ek tuh mee"],
    "mastectomy": ["mass tek tuh mee"],
    "lumpectomy": ["lump ek tuh mee"],
    "CABG": ["cabbage"],  # Coronary Artery Bypass Graft is universally "cabbage"
    "PCI": ["pee see eye"],
    # Anatomy
    "aorta": ["ay or tuh"],
    "cerebellum": ["sair uh bell um"],
    "hippocampus": ["hip oh kam pus"],
    "amygdala": ["uh mig duh luh"],
    "hypothalamus": ["hi poh thal uh mus"],
    "esophagus": ["eh sof uh gus"],
    "trachea": ["tray kee uh"],
    "larynx": ["lar inks"],
    "pharynx": ["fair inks"],
    "duodenum": ["dyu uh dee num", "dyu od en um"],
    "jejunum": ["jeh jew num"],
    "ileum": ["ill ee um"],
    "femur": ["fee mer"],
    "humerus": ["hyu mer us"],
    "clavicle": ["klav ih kul"],
    "scapula": ["skap yu luh"],
    # Specialties
    "cardiology": ["kar dee ol oh jee"],
    "oncology": ["on kol oh jee"],
    "neurology": ["nyu rol oh jee"],
    "endocrinology": ["en doh krin ol oh jee"],
    "gastroenterology": ["gas troh en ter ol oh jee"],
    "nephrology": ["neh frol oh jee"],
    "pulmonology": ["pul mon ol oh jee"],
    "rheumatology": ["roo muh tol oh jee"],
    "dermatology": ["der muh tol oh jee"],
    "ophthalmology": ["off thal mol oh jee"],
    "otolaryngology": ["oh toh lair in gol oh jee"],
    "orthopedics": ["or thoh pee diks"],
    "anesthesiology": ["an es thee zee ol oh jee"],
    "radiology": ["ray dee ol oh jee"],
    "pathology": ["puh thol oh jee"],
    "psychiatry": ["sye kye uh tree"],
    "obstetrics": ["ob stet riks"],
    "gynecology": ["gye nuh kol oh jee", "jin uh kol oh jee"],
    # ── Medical acronym misread shapes ──────────────────────────────
    # Each entry catches the plausible-English pseudo-words Whisper
    # produces when it can't tell the acronym from a real word.
    "HIPAA": ["hippa", "hippo", "hip-uh", "hip-ah", "hippah", "h-i-p-double-a"],
    "PHI": ["fee eye", "f-i", "phee-eye", "p-h-i", "fai"],
    "EHR": ["ee aitch ar", "e-h-r"],
    "EMR": ["ee em ar", "e-m-r"],
    "PTSD": ["pee tee ess dee", "petizidi", "petesedee", "petsd"],
    "ADHD": ["ay dee aitch dee", "addy h d", "add-h-d"],
    "OCD": ["oh see dee", "ocidi", "ocede"],
    "COPD": ["see oh pee dee", "copid", "copede", "co-pee-dee"],
    "GERD": ["gerd", "gurd", "gird"],
    "IBS": ["eye bee ess", "ibis", "ibbis"],
    "IBD": ["eye bee dee", "ibid", "ibide"],
    "SLE": ["ess ell ee", "slee", "sleigh"],
    "ALS": ["ay ell ess", "als", "ahls"],
    "TBI": ["tee bee eye", "tibi", "tibby"],
    "MRI": ["em ar eye", "miry", "mireye"],
    "EKG": ["ee kay gee", "ekg", "ekge"],
    "ECG": ["ee see gee", "ekg", "essegi"],
    "EEG": ["ee ee gee", "eeg", "eege"],
    "CBC": ["see bee see", "cb-see", "cbcee"],
    "BUN": ["bee you en", "bun", "buhn"],
    "HbA1c": ["aitch bee ay one see", "h-b-a-one-c", "h-b-a-1-c", "hbaonec"],
    "LDL": ["ell dee ell", "lidil", "ledel"],
    "HDL": ["aitch dee ell", "hidil", "hedel"],
    "BMI": ["bee em eye", "bimi", "bimmy"],
    "ICU": ["eye see you", "icu", "icyoo", "i-see-you"],
    "NICU": ["nick you", "nick-you", "nickyou", "nick-u"],
    "PICU": ["pick you", "pick-you", "pickyou", "pick-u"],
    "ER": ["ee ar", "er"],
    "PACU": ["pak you", "pack-you", "pa-cu", "packyou"],
    "NPO": ["en pee oh", "nipo", "nee-poh"],
    "PRN": ["pee ar en", "prin", "pee-r-n"],
    "STAT": ["stat", "staht"],
    "SOB": ["ess oh bee", "sob", "sobb"],
    "DNR": ["dee en ar", "diner", "dyner"],
    "DNI": ["dee en eye", "deny", "den-eye"],
    "CPR": ["see pee ar", "ciper", "syper"],
    "AED": ["ay ee dee", "aid", "aide"],
    "BLS": ["bee ell ess", "blss", "biles"],
    "ACLS": ["ay see ell ess", "ackles", "akless", "aclis"],
    "PEA": ["pee ee ay", "pea", "pee-ay"],
    "ROSC": ["rosk", "rosc", "rosec"],
    "ESRD": ["ee ess ar dee", "eserd", "ezerd"],
    "BPH": ["bee pee aitch", "bph", "buf"],
    "CHF": ["see aitch ef", "chiff", "chef"],
    "DVT": ["dee vee tee", "divit", "devit"],
    "UTI": ["you tee eye", "uti", "yoo-tee-eye"],
    "CKD": ["see kay dee", "cked", "ckedi"],
}


def iter_terms() -> Iterable[RawTerm]:
    seen: set[str] = set()
    for canonical, gloss, subcat in _TERMS:
        key = canonical.lower()
        if key in seen:
            continue
        seen.add(key)
        # Medical acronyms get critical-tier 0.95 — they're frequently
        # spoken in clinical recordings and Whisper produces confident
        # pseudo-word misreads ("hippa"/"hippo" for HIPAA, "petsd" for
        # PTSD) that the standard 3-gate test would miss.
        if subcat == "med_acronym":
            score = 0.95
        elif subcat in {"drug_brand", "condition", "specialty"}:
            score = 0.7
        else:
            score = 0.55
        # Prefer explicit pronunciation when curated; otherwise leave
        # blank (Whisper handles common medical terms fine without
        # phonetic hints — only the hard cases are in _MED_PRONUNCIATIONS).
        explicit = _MED_PRONUNCIATIONS.get(canonical, [])
        if canonical.isupper() and len(canonical) <= 6:
            sounds_like = derive_acronym_pronunciations(canonical, extra_hints=explicit)
        else:
            sounds_like = list(explicit)
        yield RawTerm(
            term=canonical,
            canonical_form=canonical,
            category="medical",
            subcategory=subcat,
            sounds_like=sounds_like,
            context_blurb=gloss[:140],
            popularity_score=score,
            source="Curated medical terms",
        )
    logger.info("Medical (curated): %d terms yielded", len(seen))


name = "Medical Terms (Curated)"
category = "medical"
