"""Curated military acronyms — comprehensive across all branches.

Hand-curated from DoD usage. Covers:

- Documentation / orders / regulations: MARCORSEPMAN, MARADMIN,
  NAVADMIN, ALARACT, ALMAR, MILPER, MCO, MCBUL, OPNAVINST, MARDEPMAN.
- Units / commands across all six branches plus joint commands.
- Personnel / administrative shorthand (PCS, TAD, BAH, BAS, ETS,
  MOS, NEC).
- Operations / tactical (OPORD, FRAGO, CONOP, AAR).
- Equipment / radios / vehicles (SINCGARS, MRAP, JLTV, F-35).

Each entry carries explicit pronunciation hints in `sounds_like`
when the acronym is spoken as a word in real usage (MCWL = "mic-wil",
MARFORPAC = "mar-for-pack"). The pronunciation helper auto-derives
the letter-by-letter form on top.

Source: DoD usage (public domain; specific terminology not copyrightable).
License: Public domain.
"""

from __future__ import annotations

import logging
from typing import Iterable

from ..pronunciation import derive_acronym_pronunciations
from ..types import RawTerm

logger = logging.getLogger(__name__)


# (canonical, expansion, subcategory, [extra pronunciation hints])
# Pronunciation hints are SPOKEN forms — write them the way the
# acronym sounds in real conversations. Empty list = auto-derive
# letter-by-letter only.
_ACRONYMS: list[tuple[str, str, str, list[str]]] = [
    # ── Marine Corps documentation / orders / regulations ─────────────
    ("MARADMIN", "Marine Corps Administrative Message", "usmc_doc",
     ["mar admin", "mar-admin"]),
    ("MARCORSEPMAN", "Marine Corps Separation and Retirement Manual", "usmc_doc",
     ["mar corps sep man", "mar-corps-sep-man"]),
    ("MARCORMAN", "Marine Corps Manpower Manual", "usmc_doc",
     ["mar corps man", "mar-corps-man"]),
    ("MCO", "Marine Corps Order", "usmc_doc",
     ["em see oh"]),
    ("MCBUL", "Marine Corps Bulletin", "usmc_doc",
     ["em see bull", "mar bull", "marbull"]),
    ("MCRP", "Marine Corps Reference Publication", "usmc_doc", []),
    ("MCWP", "Marine Corps Warfighting Publication", "usmc_doc", []),
    ("MCDP", "Marine Corps Doctrinal Publication", "usmc_doc", []),
    ("MCTP", "Marine Corps Tactical Publication", "usmc_doc", []),
    ("NAVMC", "Navy/Marine Corps Form or Publication", "usmc_doc", []),
    ("MARDEPMAN", "Marine Corps Drug Demand Reduction Program Manual", "usmc_doc", []),
    ("IRAM", "Individual Records Administration Manual", "usmc_doc", []),
    ("PFTOMAN", "Performance Evaluation System Manual", "usmc_doc", []),
    # ── Marine Corps units / commands ─────────────────────────────────
    ("MCTSSA", "Marine Corps Tactical Systems Support Activity", "usmc_unit",
     ["em see tee double s ay", "em-see-tee-double-ess-ay"]),
    ("MCWL", "Marine Corps Warfighting Laboratory", "usmc_unit",
     ["mic wil", "mickwill", "mick wil"]),
    ("MARCORSYSCOM", "Marine Corps Systems Command", "usmc_unit",
     ["mar corps sys com", "mar-corps-sis-com"]),
    ("MARFORPAC", "Marine Forces Pacific", "usmc_unit",
     ["mar for pack", "mar-for-pack", "mar-fore-pack"]),
    ("MARFORLANT", "Marine Forces Atlantic", "usmc_unit",
     ["mar for lant", "mar-for-lant"]),
    ("MARFORRES", "Marine Forces Reserve", "usmc_unit",
     ["mar for res", "mar-for-res"]),
    ("MARFOREUR", "Marine Forces Europe", "usmc_unit",
     ["mar for yer", "mar-for-yur"]),
    ("MARFORAF", "Marine Forces Africa", "usmc_unit",
     ["mar for af", "mar-for-af"]),
    ("MARFORCYBER", "Marine Forces Cyber", "usmc_unit",
     ["mar for cyber", "mar-for-cyber"]),
    ("MARFORSOC", "Marine Forces Special Operations Command", "usmc_unit",
     ["mar for sock", "mar-for-sock"]),
    ("MARFORSTRAT", "Marine Forces Strategic Command", "usmc_unit", []),
    ("MARSOC", "Marine Forces Special Operations Command", "usmc_unit",
     ["mar sock", "mar-sock"]),
    ("MCESG", "Marine Corps Embassy Security Group", "usmc_unit", []),
    ("MCRC", "Marine Corps Recruiting Command", "usmc_unit", []),
    ("MCIA", "Marine Corps Intelligence Activity", "usmc_unit", []),
    ("MCIWS", "Marine Corps Instructor of Water Survival", "usmc_unit", []),
    ("MCAGCC", "Marine Corps Air Ground Combat Center", "usmc_unit",
     ["em see ay gee see see"]),
    ("MAGTF", "Marine Air-Ground Task Force", "usmc_unit",
     ["mag taf", "mag-taf"]),
    ("MEU", "Marine Expeditionary Unit", "usmc_unit",
     ["em ee you", "em-ee-you"]),
    ("MEF", "Marine Expeditionary Force", "usmc_unit",
     ["em ee ef", "em-ee-ef"]),
    ("MARDIV", "Marine Division", "usmc_unit",
     ["mar div", "mar-div"]),
    ("MAW", "Marine Aircraft Wing", "usmc_unit",
     ["em ay double-u"]),
    ("MLG", "Marine Logistics Group", "usmc_unit", []),
    ("MARSOR", "Marine Special Operations Regiment", "usmc_unit",
     ["mar sore"]),
    ("MARSOB", "Marine Special Operations Battalion", "usmc_unit", []),
    ("MARSOT", "Marine Special Operations Team", "usmc_unit", []),
    ("FMF", "Fleet Marine Force", "usmc_unit", []),
    ("FMFM", "Fleet Marine Force Manual", "usmc_unit", []),
    ("HQMC", "Headquarters Marine Corps", "usmc_unit", []),
    ("CMC", "Commandant of the Marine Corps", "usmc_unit", []),
    ("ACMC", "Assistant Commandant of the Marine Corps", "usmc_unit", []),
    ("SMMC", "Sergeant Major of the Marine Corps", "usmc_unit", []),
    ("TBS", "The Basic School (USMC officer)", "usmc_unit",
     ["tee bee ess"]),
    ("OCS", "Officer Candidate School", "usmc_unit", []),
    ("EWS", "Expeditionary Warfare School", "usmc_unit", []),
    ("CSC", "Command and Staff College", "usmc_unit", []),
    ("MCRD", "Marine Corps Recruit Depot", "usmc_unit", []),
    # ── DoD networks / communications / cyber ─────────────────────────
    # These are catastrophic-loss class — Whisper hears NIPR/SIPR as
    # "Nipper"/"Sipper" (real-sounding English), so without explicit
    # phonetic hints the gates won't catch the substitution.
    ("MCEN", "Marine Corps Enterprise Network", "usmc_net",
     ["em see en", "em-see-en", "mcen", "em-cen", "mc en", "MCSEN", "mcsen"]),
    ("MCEN-N", "Marine Corps Enterprise Network — Non-classified", "usmc_net",
     ["em see en en", "em-see-en-en", "mcen en", "MCSEN N"]),
    ("MCEN-S", "Marine Corps Enterprise Network — Secret", "usmc_net",
     ["em see en ess", "em-see-en-ess", "MCSEN S"]),
    ("NIPR", "Non-classified Internet Protocol Router", "dod_net",
     ["en eye pee ar", "en-eye-pee-ar", "nipper", "Nipper", "nip-er", "nipr",
      "non secure ip router"]),
    ("SIPR", "Secret Internet Protocol Router", "dod_net",
     ["ess eye pee ar", "ess-eye-pee-ar", "sipper", "Sipper", "sip-er", "sipr",
      "secret ip router"]),
    ("NIPRNet", "Non-classified Internet Protocol Router Network", "dod_net",
     ["en eye pee ar net", "nipr net", "nipr-net", "Nipper net", "Nippernet"]),
    ("SIPRNet", "Secret Internet Protocol Router Network", "dod_net",
     ["ess eye pee ar net", "sipr net", "sipr-net", "Sipper net", "Sippernet"]),
    ("JWICS", "Joint Worldwide Intelligence Communications System", "dod_net",
     ["jay double-u eye see ess", "jay-wicks", "jaywix", "j-wix", "jaywicks"]),
    ("DODIN", "DoD Information Network", "dod_net",
     ["dee oh dee eye en", "dod-in", "dohdin", "doh-din", "doh-d-in"]),
    ("DISA", "Defense Information Systems Agency", "dod_net",
     ["dee eye ess ay", "dee-sah", "die-sah"]),
    ("DISN", "Defense Information Systems Network", "dod_net",
     ["dee eye ess en", "dee-sin", "dis-en"]),
    ("DSN", "Defense Switched Network", "dod_net",
     ["dee ess en", "dee-ess-en"]),
    ("VOSIP", "Voice over Secure Internet Protocol", "dod_net",
     ["vee oh ess eye pee", "voh-sip", "voe-sip"]),
    ("SVOIP", "Secure Voice over Internet Protocol", "dod_net",
     ["ess vee oh eye pee", "es-voip", "ess voip"]),
    ("CAC", "Common Access Card", "dod_net",
     ["see ay see", "cack"]),
    ("PIV", "Personal Identity Verification", "dod_net",
     ["pee eye vee", "piv"]),
    ("STIG", "Security Technical Implementation Guide", "dod_net",
     ["ess tee eye gee", "stig"]),
    ("ATO", "Authorization to Operate", "dod_net",
     ["ay tee oh", "ah-toe", "atto"]),
    ("IATT", "Interim Authorization to Test", "dod_net",
     ["eye ay tee tee", "eye-at"]),
    ("RMF", "Risk Management Framework", "dod_net",
     ["ar em ef", "rmf"]),
    ("FedRAMP", "Federal Risk and Authorization Management Program", "dod_net",
     ["fed ramp", "fed-ramp"]),
    ("CMMC", "Cybersecurity Maturity Model Certification", "dod_net",
     ["see em em see", "see-em-em-see"]),
    # ── 1st MOG / Marine Communications units ─────────────────────────
    ("1stMOG", "1st Marine Operations Group (Communications)", "usmc_unit",
     ["first em oh gee", "first mog", "1st mog", "first-mog", "FirstMOG"]),
    ("MARMOG", "Marine Marine Operations Group", "usmc_unit",
     ["mar mog", "mar-mog"]),
    ("MARCOMM", "Marine Corps Communications", "usmc_unit",
     ["mar com", "mar-com"]),
    # ── Navy documents / messages ─────────────────────────────────────
    ("NAVADMIN", "Naval Administrative Message", "usn_doc",
     ["nav admin", "nav-admin"]),
    ("ALNAV", "All Navy Message", "usn_doc",
     ["al nav", "al-nav"]),
    ("NAVOP", "Navy Operations Message", "usn_doc", []),
    ("OPNAVINST", "Office of the Chief of Naval Operations Instruction", "usn_doc",
     ["op nav inst", "op-nav-inst"]),
    ("SECNAVINST", "Secretary of the Navy Instruction", "usn_doc", []),
    ("BUMEDINST", "Bureau of Medicine and Surgery Instruction", "usn_doc",
     ["bu med inst", "bu-med-inst"]),
    ("BUPERSINST", "Bureau of Naval Personnel Instruction", "usn_doc",
     ["bu pers inst", "bu-pers-inst"]),
    # ── Navy commands / units ─────────────────────────────────────────
    ("USFF", "United States Fleet Forces Command", "usn_unit", []),
    ("USFLTFORCOM", "U.S. Fleet Forces Command", "usn_unit", []),
    ("PACFLT", "Pacific Fleet", "usn_unit",
     ["pack fleet"]),
    ("USPACFLT", "U.S. Pacific Fleet", "usn_unit", []),
    ("LANTFLT", "Atlantic Fleet", "usn_unit",
     ["lant fleet"]),
    ("USNAVEUR", "U.S. Naval Forces Europe", "usn_unit",
     ["yu ess nav yur", "you ess nav yur"]),
    ("USNAVCENT", "U.S. Naval Forces Central Command", "usn_unit",
     ["yu ess nav cent", "you ess nav cent"]),
    ("BUMED", "Bureau of Medicine and Surgery", "usn_unit",
     ["bu med", "bu-med", "bee yu med"]),
    ("BUPERS", "Bureau of Naval Personnel", "usn_unit",
     ["bu pers", "bu-pers"]),
    ("NETC", "Naval Education and Training Command", "usn_unit", []),
    ("NAVSEA", "Naval Sea Systems Command", "usn_unit",
     ["nav see"]),
    ("NAVAIR", "Naval Air Systems Command", "usn_unit",
     ["nav air", "nav-air"]),
    ("SPAWAR", "Space and Naval Warfare Systems Command", "usn_unit",
     ["spa war", "spa-war"]),
    ("NAVWAR", "Naval Information Warfare Systems Command", "usn_unit",
     ["nav war", "nav-war"]),
    ("ONI", "Office of Naval Intelligence", "usn_unit", []),
    ("NSIC", "Naval Strike and Air Warfare Center", "usn_unit", []),
    ("USNA", "U.S. Naval Academy", "usn_unit", []),
    ("CNO", "Chief of Naval Operations", "usn_unit", []),
    ("VCNO", "Vice Chief of Naval Operations", "usn_unit", []),
    ("MCPON", "Master Chief Petty Officer of the Navy", "usn_unit",
     ["em see pon", "mick pon"]),
    # ── Army documents / messages ─────────────────────────────────────
    ("ALARACT", "All Army Activities Message", "army_doc",
     ["al ar act", "ala ract"]),
    ("MILPER", "Military Personnel Message", "army_doc",
     ["mil per", "mil-per"]),
    ("AR", "Army Regulation", "army_doc",
     ["ay ar"]),
    ("DA Pam", "Department of the Army Pamphlet", "army_doc",
     ["dee ay pam"]),
    ("FM", "Field Manual", "army_doc", []),
    ("ATP", "Army Techniques Publication", "army_doc", []),
    ("TM", "Technical Manual", "army_doc", []),
    ("ADP", "Army Doctrine Publication", "army_doc", []),
    ("ADRP", "Army Doctrine Reference Publication", "army_doc", []),
    # ── Army commands / units ─────────────────────────────────────────
    ("USARCENT", "U.S. Army Central", "army_unit",
     ["yu ess ar cent"]),
    ("USAREUR", "U.S. Army Europe", "army_unit",
     ["yu ess ar yur"]),
    ("USARPAC", "U.S. Army Pacific", "army_unit",
     ["yu ess ar pack", "you-ess-ar-pack"]),
    ("USARSO", "U.S. Army South", "army_unit", []),
    ("USAFRICOM", "U.S. Africa Command (Army component)", "army_unit", []),
    ("FORSCOM", "U.S. Army Forces Command", "army_unit",
     ["force com", "fors com"]),
    ("TRADOC", "U.S. Army Training and Doctrine Command", "army_unit",
     ["tray dock", "trade ock"]),
    ("AMC", "U.S. Army Materiel Command", "army_unit", []),
    ("USASOC", "U.S. Army Special Operations Command", "army_unit",
     ["you ess ay sock"]),
    ("USACE", "U.S. Army Corps of Engineers", "army_unit",
     ["you ess ay see ee"]),
    ("USMA", "U.S. Military Academy (West Point)", "army_unit", []),
    ("CSM", "Command Sergeant Major", "army_unit", []),
    ("SMA", "Sergeant Major of the Army", "army_unit", []),
    # ── Air Force documents / messages ─────────────────────────────────
    ("AFI", "Air Force Instruction", "usaf_doc",
     ["ay ef eye"]),
    ("AFMAN", "Air Force Manual", "usaf_doc",
     ["ay ef man", "af man"]),
    ("AFPAM", "Air Force Pamphlet", "usaf_doc", []),
    ("AFGM", "Air Force Guidance Memorandum", "usaf_doc", []),
    ("AFPD", "Air Force Policy Directive", "usaf_doc", []),
    # ── Air Force commands / units ─────────────────────────────────────
    ("AFGSC", "Air Force Global Strike Command", "usaf_unit", []),
    ("AFMC", "Air Force Materiel Command", "usaf_unit", []),
    ("ACC", "Air Combat Command", "usaf_unit", []),
    ("AMC", "Air Mobility Command", "usaf_unit", []),
    ("AETC", "Air Education and Training Command", "usaf_unit", []),
    ("PACAF", "Pacific Air Forces", "usaf_unit",
     ["pack af", "pack-af"]),
    ("USAFE", "U.S. Air Forces in Europe", "usaf_unit",
     ["yu safe", "you-safe"]),
    ("AFRL", "Air Force Research Laboratory", "usaf_unit", []),
    ("AFSOC", "Air Force Special Operations Command", "usaf_unit",
     ["af sock", "af-sock"]),
    ("AFCYBER", "Air Forces Cyber", "usaf_unit", []),
    ("USAFA", "U.S. Air Force Academy", "usaf_unit", []),
    ("CSAF", "Chief of Staff of the Air Force", "usaf_unit", []),
    ("CMSAF", "Chief Master Sergeant of the Air Force", "usaf_unit", []),
    # ── Coast Guard documents / messages ──────────────────────────────
    ("ALCOAST", "All Coast Guard Message", "uscg_doc",
     ["al coast", "al-coast"]),
    ("CGMSG", "Coast Guard Message", "uscg_doc", []),
    ("COMDTINST", "Commandant Instruction (USCG)", "uscg_doc",
     ["com dee tee inst", "com-dee-tee-inst"]),
    ("COMDTNOTE", "Commandant Notice (USCG)", "uscg_doc", []),
    # ── Space Force documents / messages ──────────────────────────────
    ("ALSPACE", "All Space Force Message", "ussf_doc",
     ["al space", "al-space"]),
    ("SPFORINST", "Space Force Instruction", "ussf_doc", []),
    ("SPFORMAN", "Space Force Manual", "ussf_doc", []),
    # ── Army messages (additional) ────────────────────────────────────
    ("ALMAR", "All Marine Corps Message", "usmc_doc",
     ["al mar", "al-mar"]),
    ("CMMI", "Commandant of the Marine Corps Message", "usmc_doc",
     ["see em em eye"]),
    ("ALARMY", "All Army Message", "army_doc",
     ["al army", "al-army"]),
    ("ALMARFOR", "All MARFOR Cyber Message", "usmc_doc",
     ["al mar for"]),
    # ── Coast Guard / Space Force units ───────────────────────────────
    ("USCGC", "U.S. Coast Guard Cutter", "uscg_unit", []),
    ("CGAS", "Coast Guard Air Station", "uscg_unit", []),
    ("MSST", "Maritime Safety and Security Team", "uscg_unit", []),
    ("MCPOCG", "Master Chief Petty Officer of the Coast Guard", "uscg_unit", []),
    ("USSF", "United States Space Force", "ussf_unit",
     ["yu ess es ef"]),
    ("SPACEOPSCOM", "Space Operations Command", "ussf_unit", []),
    ("SSC", "Space Systems Command", "ussf_unit", []),
    ("STARCOM", "Space Training and Readiness Command", "ussf_unit",
     ["star com", "star-com"]),
    ("CMSSF", "Chief Master Sergeant of the Space Force", "ussf_unit", []),
    # ── Joint commands ────────────────────────────────────────────────
    ("USCENTCOM", "U.S. Central Command", "joint_command",
     ["cent com", "you-ess-cent-com"]),
    ("USPACOM", "U.S. Pacific Command (legacy name)", "joint_command",
     ["pay-com", "pa-com"]),
    ("USINDOPACOM", "U.S. Indo-Pacific Command", "joint_command",
     ["indo pa com", "indo-pa-com"]),
    ("USEUCOM", "U.S. European Command", "joint_command",
     ["yu com", "you-com", "yur-com"]),
    ("USAFRICOM", "U.S. Africa Command", "joint_command",
     ["af-ri-com", "afri-com"]),
    ("USNORTHCOM", "U.S. Northern Command", "joint_command",
     ["north com", "north-com"]),
    ("USSOUTHCOM", "U.S. Southern Command", "joint_command",
     ["south com", "south-com"]),
    ("USSOCOM", "U.S. Special Operations Command", "joint_command",
     ["sock com", "sock-com"]),
    ("USTRANSCOM", "U.S. Transportation Command", "joint_command",
     ["trans com", "trans-com"]),
    ("USCYBERCOM", "U.S. Cyber Command", "joint_command",
     ["cyber com", "cyber-com"]),
    ("USSTRATCOM", "U.S. Strategic Command", "joint_command",
     ["strat com", "strat-com"]),
    ("USSPACECOM", "U.S. Space Command", "joint_command",
     ["space com", "space-com"]),
    ("CENTCOM", "Central Command", "joint_command",
     ["cent com", "cent-com"]),
    ("PACOM", "Pacific Command", "joint_command",
     ["pa com", "pay-com"]),
    ("INDOPACOM", "Indo-Pacific Command", "joint_command",
     ["indo pa com", "indo-pa-com"]),
    ("SOUTHCOM", "Southern Command", "joint_command",
     ["south com"]),
    ("NORTHCOM", "Northern Command", "joint_command",
     ["north com"]),
    ("AFRICOM", "Africa Command", "joint_command",
     ["af-ri-com"]),
    ("EUCOM", "European Command", "joint_command",
     ["yu com"]),
    ("SOCOM", "Special Operations Command", "joint_command",
     ["sock com"]),
    ("TRANSCOM", "Transportation Command", "joint_command",
     ["trans com"]),
    ("CYBERCOM", "Cyber Command", "joint_command",
     ["cyber com"]),
    ("STRATCOM", "Strategic Command", "joint_command",
     ["strat com"]),
    ("SPACECOM", "Space Command", "joint_command",
     ["space com"]),
    ("NORAD", "North American Aerospace Defense Command", "joint_command",
     ["nor-ad", "nor add"]),
    ("JCS", "Joint Chiefs of Staff", "joint_command", []),
    ("CJCS", "Chairman of the Joint Chiefs of Staff", "joint_command", []),
    ("VCJCS", "Vice Chairman of the Joint Chiefs of Staff", "joint_command", []),
    ("OSD", "Office of the Secretary of Defense", "joint_command", []),
    ("SecDef", "Secretary of Defense", "joint_command",
     ["sec def", "sec-def"]),
    ("DepSecDef", "Deputy Secretary of Defense", "joint_command", []),
    ("DSCA", "Defense Security Cooperation Agency", "joint_command", []),
    ("DLA", "Defense Logistics Agency", "joint_command", []),
    ("DTRA", "Defense Threat Reduction Agency", "joint_command", []),
    ("DARPA", "Defense Advanced Research Projects Agency", "joint_command",
     ["dar pa", "dar-pa"]),
    ("DHA", "Defense Health Agency", "joint_command", []),
    ("DCSA", "Defense Counterintelligence and Security Agency", "joint_command", []),
    ("DCMA", "Defense Contract Management Agency", "joint_command", []),
    ("DCAA", "Defense Contract Audit Agency", "joint_command", []),
    ("DFAS", "Defense Finance and Accounting Service", "joint_command",
     ["dee fas", "dee-fas"]),
    ("DPAS", "Defense Property Accountability System", "joint_command", []),
    # ── Personnel / administrative ─────────────────────────────────────
    ("ADSEP", "Administrative Separation", "personnel",
     ["ad sep", "ad-sep"]),
    ("PCS", "Permanent Change of Station", "personnel",
     ["pee see ess"]),
    ("TAD", "Temporary Additional Duty", "personnel",
     ["tee ay dee"]),
    ("TDY", "Temporary Duty", "personnel",
     ["tee dee why"]),
    ("BAH", "Basic Allowance for Housing", "personnel",
     ["bee ay aitch"]),
    ("BAS", "Basic Allowance for Subsistence", "personnel",
     ["bee ay ess"]),
    ("ETS", "Expiration Term of Service", "personnel",
     ["ee tee ess"]),
    ("EAS", "End of Active Service", "personnel",
     ["ee ay ess"]),
    ("MOS", "Military Occupational Specialty", "personnel",
     ["em oh ess"]),
    ("AFSC", "Air Force Specialty Code", "personnel",
     ["ay ef ess see"]),
    ("NEC", "Navy Enlisted Classification", "personnel",
     ["en ee see"]),
    ("MOSC", "Military Occupational Specialty Code", "personnel", []),
    ("MPF", "Military Personnel Flight", "personnel", []),
    ("RDML", "Rear Admiral Lower Half", "personnel",
     ["ar dee em ell"]),
    ("ROTC", "Reserve Officer Training Corps", "personnel",
     ["rot see", "ar oh tee see"]),
    ("OPMS", "Officer Personnel Management System", "personnel", []),
    ("EPR", "Enlisted Performance Report", "personnel", []),
    ("OER", "Officer Evaluation Report", "personnel", []),
    ("FITREP", "Fitness Report", "personnel",
     ["fit rep", "fit-rep"]),
    ("LES", "Leave and Earnings Statement", "personnel",
     ["ell ee ess"]),
    ("DD214", "Certificate of Release or Discharge from Active Duty", "personnel",
     ["dee dee two fourteen", "dee-dee-two-fourteen"]),
    ("UCMJ", "Uniform Code of Military Justice", "personnel",
     ["you see em jay"]),
    ("NJP", "Non-Judicial Punishment", "personnel",
     ["en jay pee"]),
    ("AWOL", "Absent Without Leave", "personnel",
     ["ay wol", "ay-wall"]),
    ("UA", "Unauthorized Absence", "personnel", []),
    ("BCD", "Bad Conduct Discharge", "personnel", []),
    ("OTH", "Other Than Honorable", "personnel", []),
    ("DD", "Dishonorable Discharge", "personnel", []),
    ("PEB", "Physical Evaluation Board", "personnel",
     ["pee ee bee"]),
    ("MEB", "Medical Evaluation Board", "personnel",
     ["em ee bee"]),
    ("LIMDU", "Limited Duty", "personnel",
     ["lim doo", "lim-doo"]),
    ("NAVPERS", "Navy Personnel Form", "personnel",
     ["nav pers"]),
    # ── Command, Control, Communications, Computers, Intelligence ─────
    # C-system family. Each level adds one more "C" or domain. These
    # are catastrophic-loss class — Whisper hears "see four eye" and
    # without explicit hints can't tell C4I from CAC (both DM='KK').
    ("C2", "Command and Control", "c4isr",
     ["see two", "C-2", "see-too"]),
    ("C3", "Command, Control, and Communications", "c4isr",
     ["see three", "C-3", "see-three"]),
    ("C4", "Command, Control, Communications, and Computers", "c4isr",
     ["see four", "C-4", "see-fore"]),
    ("C4I", "Command, Control, Communications, Computers, and Intelligence", "c4isr",
     ["see four eye", "C-4-I", "see-four-eye", "c4i"]),
    ("C4ISR", "Command, Control, Communications, Computers, Intelligence, Surveillance, and Reconnaissance", "c4isr",
     ["see four eye ess ar", "C-4-I-S-R", "see-four-eye-ess-ar"]),
    ("C5I", "Command, Control, Communications, Computers, Cyber, and Intelligence", "c4isr",
     ["see five eye", "C-5-I", "see-five-eye"]),
    ("C5ISR", "Command, Control, Communications, Computers, Cyber, Intelligence, Surveillance, and Reconnaissance", "c4isr",
     ["see five eye ess ar", "C-5-I-S-R"]),
    ("ISR", "Intelligence, Surveillance, and Reconnaissance", "c4isr",
     ["eye ess ar", "I-S-R"]),
    ("ISRT", "Intelligence, Surveillance, Reconnaissance, and Targeting", "c4isr",
     ["eye ess ar tee", "I-S-R-T"]),
    ("MASINT", "Measurement and Signature Intelligence", "c4isr",
     ["em ay ess int", "ma-sint", "may-sint"]),
    ("SIGINT", "Signals Intelligence", "c4isr",
     ["sig int", "SIG-int", "sigh-int"]),
    ("HUMINT", "Human Intelligence", "c4isr",
     ["hyoo mint", "hyu-mint", "hew-mint"]),
    ("OSINT", "Open Source Intelligence", "c4isr",
     ["oh sint", "oh-sint", "OH-sint"]),
    ("GEOINT", "Geospatial Intelligence", "c4isr",
     ["gee oh int", "geo-int", "JEE-oh-int"]),
    ("ELINT", "Electronic Intelligence", "c4isr",
     ["ee lint", "EE-lint", "ee-lint"]),
    ("FININT", "Financial Intelligence", "c4isr",
     ["fin int", "FIN-int"]),
    ("CYBINT", "Cyber Intelligence", "c4isr",
     ["sigh bint", "SI-bint", "cy-bint"]),
    ("TECHINT", "Technical Intelligence", "c4isr",
     ["tek int", "TEK-int"]),
    # ── Operations / tactical ─────────────────────────────────────────
    ("OPORD", "Operation Order", "operations",
     ["op ord", "op-ord"]),
    ("FRAGO", "Fragmentary Order", "operations",
     ["frag oh", "frah-go"]),
    ("WARNO", "Warning Order", "operations",
     ["war no"]),
    ("CONOP", "Concept of Operations", "operations",
     ["co nop", "co-nop"]),
    ("CONOPS", "Concept of Operations", "operations",
     ["co nops", "co-nops"]),
    ("ROE", "Rules of Engagement", "operations",
     ["ar oh ee"]),
    ("AAR", "After Action Review", "operations",
     ["ay ay ar", "triple-a-r"]),
    ("SITREP", "Situation Report", "operations",
     ["sit rep", "sit-rep"]),
    ("SPOTREP", "Spot Report", "operations",
     ["spot rep", "spot-rep"]),
    ("MEDEVAC", "Medical Evacuation", "operations",
     ["med ee vac", "medi-vac"]),
    ("CASEVAC", "Casualty Evacuation", "operations",
     ["cas ee vac", "cazi-vac"]),
    ("LZ", "Landing Zone", "operations",
     ["ell zee"]),
    ("DZ", "Drop Zone", "operations",
     ["dee zee"]),
    ("HVT", "High Value Target", "operations",
     ["aitch vee tee"]),
    ("IED", "Improvised Explosive Device", "operations",
     ["eye ee dee"]),
    ("VBIED", "Vehicle-Borne IED", "operations",
     ["vee-bid", "vee bid"]),
    ("CCP", "Casualty Collection Point", "operations", []),
    ("FOB", "Forward Operating Base", "operations",
     ["ef oh bee", "fob"]),
    ("COB", "Contingency Operating Base", "operations", []),
    ("PB", "Patrol Base", "operations", []),
    ("OP", "Observation Post", "operations", []),
    ("RP", "Release Point", "operations", []),
    ("LD", "Line of Departure", "operations", []),
    ("PL", "Phase Line", "operations", []),
    ("EA", "Engagement Area", "operations", []),
    ("NAI", "Named Area of Interest", "operations",
     ["en ay eye"]),
    ("TAI", "Targeted Area of Interest", "operations",
     ["tee ay eye"]),
    ("TIC", "Troops in Contact", "operations",
     ["tic"]),
    ("CASREP", "Casualty Report", "operations",
     ["cas rep", "cas-rep"]),
    ("MASCAL", "Mass Casualty", "operations",
     ["mas cal", "mas-cal"]),
    ("MASCAS", "Mass Casualty Event", "operations", []),
    ("KIA", "Killed In Action", "operations",
     ["kay eye ay"]),
    ("WIA", "Wounded In Action", "operations",
     ["double-u eye ay"]),
    ("MIA", "Missing In Action", "operations",
     ["em eye ay"]),
    ("DOW", "Died Of Wounds", "operations", []),
    # ── Equipment / radio ─────────────────────────────────────────────
    ("SINCGARS", "Single Channel Ground and Airborne Radio System", "equipment",
     ["sin gars", "sin-gars"]),
    ("MRAP", "Mine-Resistant Ambush Protected", "equipment",
     ["em-rap", "em rap"]),
    ("HMMWV", "High Mobility Multipurpose Wheeled Vehicle / Humvee", "equipment",
     ["hum vee", "hum-vee", "humvee"]),
    ("Humvee", "HMMWV", "equipment", []),
    ("JLTV", "Joint Light Tactical Vehicle", "equipment", []),
    ("LAV", "Light Armored Vehicle", "equipment",
     ["lav"]),
    ("AAV", "Assault Amphibious Vehicle", "equipment", []),
    ("ACV", "Amphibious Combat Vehicle", "equipment", []),
    ("ACOG", "Advanced Combat Optical Gunsight", "equipment",
     ["ay-cog", "ay cog"]),
    ("EOTECH", "Electro-Optics Technology (red dot sight)", "equipment",
     ["ee oh tek", "eo-tech"]),
    ("PEQ-15", "Aiming Laser PEQ-15", "equipment",
     ["pek fifteen", "peq-fifteen"]),
    ("NVG", "Night Vision Goggles", "equipment",
     ["en vee gee"]),
    ("PVS-14", "Night Vision Monocular", "equipment", []),
    ("PNVS", "Pilot Night Vision System", "equipment", []),
    ("FLIR", "Forward Looking Infrared", "equipment",
     ["fleer", "fleer flir"]),
    ("M4", "M4 carbine", "equipment", []),
    ("M16", "M16 rifle", "equipment", []),
    ("M249", "M249 SAW machine gun", "equipment", []),
    ("M240", "M240 medium machine gun", "equipment", []),
    ("M2", "M2 .50 caliber machine gun", "equipment",
     ["em two"]),
    ("F-35", "F-35 Lightning II", "equipment",
     ["ef thirty-five", "ef-thirty-five"]),
    ("F-22", "F-22 Raptor", "equipment", []),
    ("F-18", "F/A-18 Hornet/Super Hornet", "equipment", []),
    ("F-15", "F-15 Eagle", "equipment", []),
    ("F-16", "F-16 Fighting Falcon", "equipment", []),
    ("V-22", "V-22 Osprey", "equipment", []),
    ("CH-53", "CH-53 Super Stallion / King Stallion", "equipment", []),
    ("UH-60", "UH-60 Black Hawk", "equipment", []),
    ("AH-64", "AH-64 Apache", "equipment", []),
    ("KC-135", "KC-135 Stratotanker", "equipment", []),
    ("C-17", "C-17 Globemaster III", "equipment", []),
    ("C-130", "C-130 Hercules", "equipment", []),
    # ── Common procedural / staff ──────────────────────────────────────
    ("LMR", "Land Mobile Radio", "procedural",
     ["ell em ar"]),
    ("RFI", "Request for Information", "procedural",
     ["ar ef eye"]),
    ("RFF", "Request for Forces", "procedural", []),
    ("CDR", "Commander", "procedural", []),
    ("CG", "Commanding General", "procedural", []),
    ("XO", "Executive Officer", "procedural",
     ["ex oh"]),
    ("S-1", "Personnel Officer (Battalion-level)", "procedural",
     ["ess one"]),
    ("S-2", "Intelligence Officer", "procedural",
     ["ess two"]),
    ("S-3", "Operations Officer", "procedural",
     ["ess three"]),
    ("S-4", "Logistics Officer", "procedural",
     ["ess four"]),
    ("S-5", "Plans Officer", "procedural", []),
    ("S-6", "Communications Officer", "procedural",
     ["ess six"]),
    ("J-1", "Joint Personnel", "procedural",
     ["jay one"]),
    ("J-2", "Joint Intelligence", "procedural",
     ["jay two"]),
    ("J-3", "Joint Operations", "procedural",
     ["jay three"]),
    ("J-4", "Joint Logistics", "procedural",
     ["jay four"]),
    ("J-5", "Joint Plans and Policy", "procedural", []),
    ("J-6", "Joint Communications", "procedural",
     ["jay six"]),
    ("J-7", "Joint Force Development", "procedural", []),
    ("J-8", "Joint Force Structure / Resource", "procedural", []),
    ("J-9", "Civil-Military Operations", "procedural", []),
    ("G-1", "General Staff Personnel", "procedural", []),
    ("G-2", "General Staff Intelligence", "procedural", []),
    ("G-3", "General Staff Operations", "procedural", []),
    ("G-4", "General Staff Logistics", "procedural", []),
    ("G-5", "General Staff Plans", "procedural", []),
    ("G-6", "General Staff Communications", "procedural", []),
    ("G-7", "General Staff Engagement", "procedural", []),
    ("G-8", "General Staff Resource Management", "procedural", []),
    ("OPSEC", "Operational Security", "procedural",
     ["op sec", "op-sec"]),
    ("PERSEC", "Personal Security", "procedural", []),
    ("COMSEC", "Communications Security", "procedural",
     ["com sec", "com-sec"]),
    ("INFOSEC", "Information Security", "procedural", []),
    ("SIGINT", "Signals Intelligence", "procedural",
     ["sig int", "sig-int"]),
    ("HUMINT", "Human Intelligence", "procedural",
     ["hyu mint", "human-int"]),
    ("OSINT", "Open Source Intelligence", "procedural",
     ["oh sint", "oh-sint"]),
    ("ELINT", "Electronic Intelligence", "procedural",
     ["ee lint"]),
    ("MASINT", "Measurement and Signature Intelligence", "procedural", []),
    ("GEOINT", "Geospatial Intelligence", "procedural",
     ["jee oh int"]),
    # ── Pay grade ─────────────────────────────────────────────────────
    ("E-1", "Pay Grade Enlisted 1", "paygrade",
     ["ee one"]),
    ("E-2", "Pay Grade Enlisted 2", "paygrade",
     ["ee two"]),
    ("E-3", "Pay Grade Enlisted 3", "paygrade",
     ["ee three"]),
    ("E-4", "Pay Grade Enlisted 4", "paygrade",
     ["ee four"]),
    ("E-5", "Pay Grade Enlisted 5", "paygrade",
     ["ee five"]),
    ("E-6", "Pay Grade Enlisted 6", "paygrade",
     ["ee six"]),
    ("E-7", "Pay Grade Enlisted 7", "paygrade",
     ["ee seven"]),
    ("E-8", "Pay Grade Enlisted 8", "paygrade",
     ["ee eight"]),
    ("E-9", "Pay Grade Enlisted 9", "paygrade",
     ["ee nine"]),
    ("O-1", "Pay Grade Officer 1", "paygrade",
     ["oh one"]),
    ("O-2", "Pay Grade Officer 2", "paygrade",
     ["oh two"]),
    ("O-3", "Pay Grade Officer 3", "paygrade",
     ["oh three"]),
    ("O-4", "Pay Grade Officer 4", "paygrade",
     ["oh four"]),
    ("O-5", "Pay Grade Officer 5", "paygrade",
     ["oh five"]),
    ("O-6", "Pay Grade Officer 6", "paygrade",
     ["oh six"]),
    ("O-7", "Pay Grade Officer 7", "paygrade",
     ["oh seven"]),
    ("O-8", "Pay Grade Officer 8", "paygrade",
     ["oh eight"]),
    ("O-9", "Pay Grade Officer 9", "paygrade",
     ["oh nine"]),
    ("O-10", "Pay Grade Officer 10", "paygrade",
     ["oh ten"]),
    ("W-1", "Warrant Officer 1", "paygrade",
     ["double-u one"]),
    ("W-2", "Chief Warrant Officer 2", "paygrade",
     ["double-u two"]),
    ("W-3", "Chief Warrant Officer 3", "paygrade",
     ["double-u three"]),
    ("W-4", "Chief Warrant Officer 4", "paygrade",
     ["double-u four"]),
    ("W-5", "Chief Warrant Officer 5", "paygrade",
     ["double-u five"]),
    # ── Bases / installations (US, frequently dictated) ──────────────
    ("Camp Pendleton", "Marine Corps base in Southern California", "installation", []),
    ("Camp Lejeune", "Marine Corps base in North Carolina", "installation",
     ["camp lah jern", "camp luh-jurn"]),
    ("Camp Geiger", "Marine training facility, NC", "installation",
     ["camp guy ger", "camp gye-gur"]),
    ("Camp Foster", "USMC base, Okinawa", "installation", []),
    ("Camp Hansen", "USMC base, Okinawa", "installation", []),
    ("Camp Schwab", "USMC base, Okinawa", "installation",
     ["camp shwab"]),
    ("Camp Kinser", "USMC base, Okinawa", "installation", []),
    ("Camp Courtney", "USMC base, Okinawa", "installation", []),
    ("Quantico", "Marine Corps Base Quantico, Virginia", "installation",
     ["kwan tih co"]),
    ("Parris Island", "Marine Corps Recruit Depot, SC", "installation", []),
    ("MCRD San Diego", "Marine Corps Recruit Depot San Diego", "installation", []),
    ("29 Palms", "Marine Corps Air Ground Combat Center", "installation",
     ["twenty nine palms"]),
    ("Twentynine Palms", "MCAGCC, Yermo CA", "installation", []),
    ("Norfolk", "Naval Station Norfolk, VA", "installation", []),
    ("San Diego", "Naval Base San Diego, CA", "installation", []),
    ("Bremerton", "Naval Base Kitsap, WA", "installation",
     ["brem er ton"]),
    ("Pearl Harbor", "Joint Base Pearl Harbor-Hickam, HI", "installation", []),
    ("Yokosuka", "U.S. Fleet Activities Yokosuka, Japan", "installation",
     ["yo koh skuh", "yo-kos-ka"]),
    ("Sasebo", "U.S. Fleet Activities Sasebo, Japan", "installation",
     ["sah seh boh"]),
    ("Fort Liberty", "Army base in NC (formerly Fort Bragg)", "installation", []),
    ("Fort Bragg", "Army base in NC (renamed Fort Liberty)", "installation", []),
    ("Fort Cavazos", "Army base in TX (formerly Fort Hood)", "installation",
     ["fort kah vah sos"]),
    ("Fort Hood", "Army base in TX (renamed Fort Cavazos)", "installation", []),
    ("Fort Moore", "Army base in GA (formerly Fort Benning)", "installation", []),
    ("Fort Benning", "Army base in GA (renamed Fort Moore)", "installation", []),
    ("Fort Campbell", "101st Airborne Division, KY/TN", "installation", []),
    ("Fort Drum", "10th Mountain Division, NY", "installation", []),
    ("Fort Riley", "1st Infantry Division, KS", "installation", []),
    ("Fort Carson", "4th Infantry Division, CO", "installation", []),
    ("Fort Stewart", "3rd Infantry Division, GA", "installation", []),
    ("West Point", "U.S. Military Academy, NY", "installation", []),
    ("Annapolis", "U.S. Naval Academy, MD", "installation",
     ["ah nap oh lis"]),
    ("Colorado Springs", "U.S. Air Force Academy", "installation", []),
    ("Wright-Patterson", "Wright-Patterson AFB, OH", "installation", []),
    ("Ramstein", "Ramstein Air Base, Germany", "installation",
     ["ram styne", "ram-styne"]),
    ("Aviano", "Aviano Air Base, Italy", "installation",
     ["ah vee ah no"]),
    ("Kadena", "Kadena Air Base, Okinawa", "installation",
     ["kah day nuh"]),
    ("Misawa", "Misawa Air Base, Japan", "installation",
     ["mee sah wah"]),
    ("Osan", "Osan Air Base, South Korea", "installation",
     ["oh san"]),
    ("Yongsan", "Yongsan Garrison, Seoul (legacy)", "installation",
     ["yong san"]),
    ("Camp Humphreys", "U.S. Army Garrison Humphreys, S. Korea", "installation", []),
    ("Diego Garcia", "U.S. Naval Support Facility, BIOT", "installation", []),
    ("Guam", "Naval Base Guam", "installation", []),
    ("Lakenheath", "RAF Lakenheath, UK", "installation",
     ["lake en heath"]),
    ("Mildenhall", "RAF Mildenhall, UK", "installation",
     ["mil den hall"]),
]


def iter_terms() -> Iterable[RawTerm]:
    seen: set[str] = set()
    for canonical, expansion, subcat, hints in _ACRONYMS:
        if canonical in seen:
            continue
        seen.add(canonical)
        # Auto-derive letter-by-letter pronunciations + merge curated hints.
        # For non-acronym entries (Camp Pendleton, F-35), only the curated
        # hints make sense. Detect by checking if the canonical is mostly
        # uppercase letters / digits / punctuation.
        if canonical.replace("-", "").replace("_", "").isalnum() and canonical.isupper():
            sounds_like = derive_acronym_pronunciations(canonical, extra_hints=hints)
        else:
            # Names like "Camp Lejeune" — only use the curated hints.
            sounds_like = list(hints)
        # All curated military acronyms get a high popularity score —
        # they're equally likely to surface in real spoken usage and
        # equally likely to be misrecognized by Whisper.
        #
        # Critical-class acronyms get a 0.95 boost so they always
        # surface in the per-category safety pool (which limits to
        # top-N by popularity). These are acronyms with a history of
        # confident-Whisper misreads ("MCTSSA" → "Mctissa"), where
        # absence from the dictionary directly produces a transcription
        # error in real user recordings. List grows as we observe more
        # regression cases.
        critical = {
            "MCTSSA", "MCWL", "MARFORPAC", "MARCORSEPMAN", "MARADMIN",
            "MARCORSYSCOM", "MARCORMAN", "MARDEPMAN", "MARFORLANT",
            "MARFORRES", "ADSEP", "MCTP", "MCWP", "MCDP", "MCRP",
            "MCBUL", "MCO", "USAFRICOM", "USCENTCOM", "USPACOM",
            # DoD network/comms — Whisper hears NIPR/SIPR as "Nipper"/
            # "Sipper" (plausible English), so these need to be in
            # retrieval for the correction phases to even consider them.
            "MCEN", "MCEN-N", "MCEN-S", "NIPR", "SIPR", "NIPRNet",
            "SIPRNet", "JWICS", "DODIN", "DISA", "DISN", "DSN",
            "1stMOG", "MARCOMM",
            # C4ISR family + intelligence disciplines — catastrophic loss
            # without sounds_like ("see four eye" → CAC because DM='KK')
            "C2", "C3", "C4", "C4I", "C4ISR", "C5I", "C5ISR",
            "ISR", "ISRT", "MASINT", "SIGINT", "HUMINT", "OSINT",
            "GEOINT", "ELINT", "FININT", "CYBINT", "TECHINT",
            # Operational acronyms commonly misread
            "ATO", "IATT", "RMF", "OPORD", "FRAGO", "CONOP", "CONOPS",
        }
        score = 0.95 if canonical in critical else 0.85
        yield RawTerm(
            term=canonical,
            canonical_form=canonical,
            category="military",
            subcategory=subcat,
            sounds_like=sounds_like,
            context_blurb=expansion[:140],
            popularity_score=score,
            source="Curated military acronyms (DoD usage, public domain)",
        )
    logger.info("Military acronyms (curated): %d yielded", len(seen))


name = "Military Acronyms (Curated)"
category = "military"
