"""Curated scientific terminology — chemistry, physics, math, biology.

Common compounds, chemical names, units, named theorems, distributions,
and Greek-letter terms that Whisper consistently mishears in scientific
podcasts and lectures. Curated rather than full PubChem extraction
because the high-frequency subset gives 90% of the value at 1% of the
size.
"""

from __future__ import annotations

import logging
from typing import Iterable

from ..pronunciation import derive_acronym_pronunciations
from ..types import RawTerm

logger = logging.getLogger(__name__)


# (canonical, gloss, subcategory, [optional pronunciation hints])
_TERMS: list[tuple[str, str, str, list[str]]] = [
    # ── Chemistry — compounds (commonly mistranscribed) ──────────────
    ("polyethylene", "common plastic polymer", "chemistry",
     ["pol ee eth uh leen"]),
    ("polypropylene", "common plastic polymer", "chemistry",
     ["pol ee proh puh leen"]),
    ("polystyrene", "plastic foam material", "chemistry",
     ["pol ee sty reen"]),
    ("polyurethane", "polymer family", "chemistry",
     ["pol ee yur uh thane"]),
    ("polyethylene terephthalate", "PET plastic", "chemistry",
     ["pol ee eth uh leen ter ef thal ate"]),
    ("polyvinyl chloride", "PVC plastic", "chemistry",
     ["pol ee vy nul klor ide"]),
    ("ethylenediaminetetraacetic acid", "EDTA chelating agent", "chemistry",
     ["eh thuh leen dye uh meen tet ruh uh see tik acid"]),
    ("EDTA", "ethylenediaminetetraacetic acid", "chemistry",
     ["ee dee tee ay"]),
    ("formaldehyde", "preservative chemical", "chemistry",
     ["for mal duh hide"]),
    ("acetaldehyde", "ethanal", "chemistry",
     ["uh seet al duh hide"]),
    ("benzene", "aromatic hydrocarbon", "chemistry",
     ["ben zeen"]),
    ("toluene", "aromatic solvent", "chemistry",
     ["tol you een"]),
    ("xylene", "aromatic solvent", "chemistry",
     ["zye leen"]),
    ("methanol", "wood alcohol", "chemistry",
     ["meth uh nawl"]),
    ("ethanol", "drinking alcohol", "chemistry",
     ["eth uh nawl"]),
    ("propanol", "isopropyl alcohol", "chemistry",
     ["proh puh nawl"]),
    ("isopropanol", "rubbing alcohol", "chemistry",
     ["eye soh proh puh nawl"]),
    ("acetone", "nail polish remover", "chemistry",
     ["ass eh tone"]),
    ("hydrochloric acid", "HCl strong acid", "chemistry",
     ["hye droh klor ik acid"]),
    ("sulfuric acid", "H2SO4 strong acid", "chemistry",
     ["sul fyur ik acid"]),
    ("nitric acid", "HNO3 strong acid", "chemistry",
     ["nye trik acid"]),
    ("phosphoric acid", "H3PO4 acid", "chemistry",
     ["fos for ik acid"]),
    ("acetic acid", "vinegar acid", "chemistry",
     ["uh see tik acid"]),
    ("ammonium nitrate", "fertilizer compound", "chemistry",
     ["uh moh nee um nye trate"]),
    ("sodium chloride", "table salt", "chemistry",
     ["soh dee um klor ide"]),
    ("calcium carbonate", "limestone compound", "chemistry",
     ["kal see um kar buh nate"]),
    ("hydrogen peroxide", "H2O2 antiseptic", "chemistry",
     ["hye druh jen per ox ide"]),
    ("ammonia", "NH3 cleaner / waste", "chemistry",
     ["uh mohn yuh"]),
    ("methamphetamine", "stimulant drug", "chemistry",
     ["meth am fet uh meen"]),
    ("amphetamine", "stimulant drug class", "chemistry",
     ["am fet uh meen"]),
    # Drugs / biotech (overlap with medical_curated, but include common ones)
    ("acetylcholine", "neurotransmitter", "chemistry",
     ["uh see tul koh leen"]),
    ("epinephrine", "adrenaline hormone", "chemistry",
     ["ep ih nef rin"]),
    ("norepinephrine", "noradrenaline hormone", "chemistry",
     ["nor ep ih nef rin"]),
    ("dopamine", "neurotransmitter", "chemistry",
     ["doh puh meen"]),
    ("serotonin", "5-HT neurotransmitter", "chemistry",
     ["sair uh toh nin"]),
    ("histamine", "allergy mediator", "chemistry",
     ["his tuh meen"]),
    ("insulin", "blood sugar hormone", "chemistry",
     ["in suh lin"]),
    ("glucagon", "blood sugar hormone", "chemistry",
     ["gloo kuh gon"]),
    ("cortisol", "stress hormone", "chemistry",
     ["kor tih sawl"]),
    ("thyroxine", "T4 thyroid hormone", "chemistry",
     ["thigh rox een"]),
    ("triiodothyronine", "T3 thyroid hormone", "chemistry",
     ["try eye oh doh thigh roh neen"]),
    ("creatinine", "muscle metabolism waste", "chemistry",
     ["kree at uh neen"]),
    ("creatine", "muscle energy molecule", "chemistry",
     ["kree uh teen"]),
    ("hemoglobin", "blood oxygen carrier", "chemistry",
     ["hee muh gloh bin"]),
    ("myoglobin", "muscle oxygen carrier", "chemistry",
     ["my oh gloh bin"]),
    ("albumin", "blood protein", "chemistry",
     ["al byu min"]),
    ("globulin", "blood protein family", "chemistry",
     ["glob yu lin"]),
    ("immunoglobulin", "antibody protein", "chemistry",
     ["im you noh glob yu lin"]),
    ("DNA", "deoxyribonucleic acid", "chemistry",
     ["dee en ay"]),
    ("RNA", "ribonucleic acid", "chemistry",
     ["ar en ay"]),
    ("mRNA", "messenger RNA", "chemistry",
     ["em ar en ay", "messenger ar en ay"]),
    ("tRNA", "transfer RNA", "chemistry",
     ["tee ar en ay"]),
    ("CRISPR", "gene editing system", "chemistry",
     ["chris per", "chris-per"]),
    ("Cas9", "CRISPR-associated protein 9", "chemistry",
     ["cass nine"]),
    # ── Physics — units ───────────────────────────────────────────────
    ("kilowatt", "1000 watts", "physics", []),
    ("megawatt", "million watts", "physics", []),
    ("gigawatt", "billion watts", "physics", []),
    ("terawatt", "trillion watts", "physics", []),
    ("kilojoule", "1000 joules", "physics", []),
    ("megajoule", "million joules", "physics", []),
    ("kilowatt-hour", "energy unit", "physics", []),
    ("kWh", "kilowatt-hour", "physics",
     ["kay double-u aitch"]),
    ("kelvin", "temperature unit", "physics", []),
    ("celsius", "temperature unit", "physics",
     ["sel see us"]),
    ("fahrenheit", "temperature unit", "physics",
     ["fair en hite"]),
    ("kilogram", "mass unit", "physics", []),
    ("kilometer", "distance unit", "physics", []),
    ("milliliter", "volume unit", "physics", []),
    ("microliter", "volume unit", "physics", []),
    ("nanosecond", "billionth of a second", "physics", []),
    ("microsecond", "millionth of a second", "physics", []),
    ("millisecond", "thousandth of a second", "physics", []),
    ("picometer", "trillionth of a meter", "physics",
     ["pee koh mee ter"]),
    ("nanometer", "billionth of a meter", "physics", []),
    ("micrometer", "millionth of a meter", "physics", []),
    ("Hertz", "frequency unit", "physics", []),
    ("kilohertz", "1000 Hz", "physics", []),
    ("megahertz", "million Hz", "physics", []),
    ("gigahertz", "billion Hz", "physics", []),
    ("terahertz", "trillion Hz", "physics", []),
    ("Pascal", "pressure unit", "physics",
     ["pas cal"]),
    ("Newton", "force unit", "physics", []),
    ("watt", "power unit", "physics", []),
    ("ampere", "current unit", "physics",
     ["am peer"]),
    ("amp", "ampere", "physics", []),
    ("volt", "voltage unit", "physics", []),
    ("ohm", "resistance unit", "physics", []),
    ("coulomb", "electric charge unit", "physics",
     ["koo lom", "koo-lom"]),
    ("farad", "capacitance unit", "physics",
     ["fair ad", "fair-ad"]),
    ("henry", "inductance unit", "physics", []),
    ("tesla", "magnetic flux density", "physics", []),
    ("weber", "magnetic flux unit", "physics",
     ["vay ber", "way ber"]),
    ("siemens", "conductance unit", "physics",
     ["see mens"]),
    ("becquerel", "radioactivity unit", "physics",
     ["beck uh rell"]),
    ("sievert", "radiation dose unit", "physics",
     ["see vurt"]),
    ("gray", "absorbed dose unit", "physics", []),
    # ── Physics — concepts ────────────────────────────────────────────
    ("entropy", "thermodynamic disorder", "physics", []),
    ("enthalpy", "thermodynamic energy", "physics",
     ["en thal pee"]),
    ("exothermic", "heat-releasing", "physics",
     ["ex oh ther mik"]),
    ("endothermic", "heat-absorbing", "physics",
     ["en doh ther mik"]),
    ("kinetic energy", "energy of motion", "physics", []),
    ("potential energy", "stored energy", "physics", []),
    ("electromagnetic", "EM wave / field", "physics",
     ["ee lek troh mag net ik"]),
    ("electromagnetism", "EM force", "physics",
     ["ee lek troh mag nuh tiz um"]),
    ("electrostatic", "static electricity", "physics", []),
    ("photon", "quantum of light", "physics", []),
    ("electron", "negative subatomic particle", "physics", []),
    ("proton", "positive subatomic particle", "physics", []),
    ("neutron", "neutral subatomic particle", "physics", []),
    ("neutrino", "nearly-massless particle", "physics",
     ["new tree no", "noo tree noh"]),
    ("quark", "elementary particle", "physics", []),
    ("boson", "force-carrier particle", "physics",
     ["boh zon"]),
    ("fermion", "matter particle", "physics",
     ["fer mee on"]),
    ("Higgs boson", "Higgs field excitation", "physics",
     ["higs boh zon"]),
    ("isotope", "nuclide variant", "physics",
     ["eye suh tope"]),
    ("isomer", "structural variant", "physics",
     ["eye suh mer"]),
    # ── Math / stats — Greek letters spelled out ─────────────────────
    ("alpha", "Greek letter α", "math", []),
    ("beta", "Greek letter β", "math", []),
    ("gamma", "Greek letter γ", "math", []),
    ("delta", "Greek letter δ", "math", []),
    ("epsilon", "Greek letter ε", "math",
     ["ep si lon"]),
    ("zeta", "Greek letter ζ", "math",
     ["zay tah", "zee tah"]),
    ("eta", "Greek letter η", "math",
     ["ay tah", "ee tah"]),
    ("theta", "Greek letter θ", "math",
     ["thay tah", "thee tah"]),
    ("iota", "Greek letter ι", "math",
     ["eye oh tah"]),
    ("kappa", "Greek letter κ", "math", []),
    ("lambda", "Greek letter λ", "math", []),
    ("mu", "Greek letter μ", "math",
     ["myoo"]),
    ("nu", "Greek letter ν", "math",
     ["noo", "nyoo"]),
    ("xi", "Greek letter ξ", "math",
     ["zye", "ksee"]),
    ("omicron", "Greek letter ο", "math",
     ["oh mih kron"]),
    ("pi", "Greek letter π", "math",
     ["pye"]),
    ("rho", "Greek letter ρ", "math",
     ["roh"]),
    ("sigma", "Greek letter σ", "math", []),
    ("tau", "Greek letter τ", "math",
     ["tow"]),
    ("upsilon", "Greek letter υ", "math",
     ["up si lon"]),
    ("phi", "Greek letter φ", "math",
     ["fye", "fee"]),
    ("chi", "Greek letter χ", "math",
     ["kye", "kee"]),
    ("psi", "Greek letter ψ", "math",
     ["sye", "psy"]),
    ("omega", "Greek letter ω", "math",
     ["oh meg uh", "oh may guh"]),
    # Statistics
    ("p-value", "probability value", "math",
     ["pee value"]),
    ("R-squared", "coefficient of determination", "math",
     ["ar squared"]),
    ("z-score", "standard score", "math",
     ["zee score"]),
    ("t-test", "Student's t-test", "math",
     ["tee test"]),
    ("chi-square", "χ² test", "math",
     ["kye square", "ky square"]),
    ("ANOVA", "analysis of variance", "math",
     ["uh noh vah", "ay noh vah"]),
    ("MANOVA", "multivariate ANOVA", "math",
     ["muh noh vah"]),
    ("ANCOVA", "analysis of covariance", "math",
     ["an koh vah"]),
    ("Bayesian", "Bayesian inference", "math",
     ["bay zee un", "bay zhun"]),
    ("frequentist", "frequentist statistics", "math",
     ["free kwen tist"]),
    ("Gaussian", "Gaussian distribution", "math",
     ["gow see un"]),
    ("Poisson", "Poisson distribution", "math",
     ["pwah son", "poy sahn"]),
    ("Bernoulli", "Bernoulli distribution", "math",
     ["bur new lee"]),
    ("binomial", "binomial distribution", "math",
     ["bye no mee al"]),
    ("multinomial", "multinomial distribution", "math",
     ["mul ti no mee al"]),
    ("logarithm", "log function", "math",
     ["log uh rith um"]),
    ("exponent", "exponent", "math", []),
    ("derivative", "calculus derivative", "math", []),
    ("integral", "calculus integral", "math", []),
    ("eigenvector", "eigenvector", "math",
     ["eye gen vek tor"]),
    ("eigenvalue", "eigenvalue", "math",
     ["eye gen val you"]),
    ("matrix", "rectangular array", "math", []),
    ("vector", "directed quantity", "math", []),
    ("tensor", "multi-dimensional array", "math", []),
    ("scalar", "single number", "math", []),
]


def iter_terms() -> Iterable[RawTerm]:
    seen: set[str] = set()
    for canonical, gloss, subcat, hints in _TERMS:
        key = canonical.lower()
        if key in seen:
            continue
        seen.add(key)
        # Auto-derive letter-by-letter for short uppercase acronyms;
        # otherwise use only the curated hints.
        if (
            canonical.replace("-", "").replace("_", "").isalnum()
            and canonical.isupper()
            and len(canonical) <= 6
        ):
            sounds_like = derive_acronym_pronunciations(canonical, extra_hints=hints)
        else:
            sounds_like = list(hints)
        score = 0.6
        yield RawTerm(
            term=canonical,
            canonical_form=canonical,
            category="science",
            subcategory=subcat,
            sounds_like=sounds_like,
            context_blurb=gloss[:140],
            popularity_score=score,
            source="Curated scientific / chemistry / physics / math terms",
        )
    logger.info("Science terms (curated): %d yielded", len(seen))


name = "Science Terms (Curated)"
category = "science"
