"""Curated tech terms — frameworks, languages, tools, services.

Hand-curated set of the brands/tools/concepts engineers actually say
in transcripts. Cross-checked against Stack Overflow's most-tagged
list, awesome-x repos, and major cloud-provider product names.
"""

from __future__ import annotations

import logging
from typing import Iterable

from ..pronunciation import derive_acronym_pronunciations
from ..types import RawTerm

logger = logging.getLogger(__name__)


_TERMS: list[tuple[str, str, str]] = [
    # Programming languages
    ("Python", "programming language", "language"),
    ("JavaScript", "programming language", "language"),
    ("TypeScript", "programming language", "language"),
    ("Java", "programming language", "language"),
    ("C++", "programming language", "language"),
    ("C#", "programming language", "language"),
    ("Ruby", "programming language", "language"),
    ("Rust", "programming language", "language"),
    ("Go", "programming language", "language"),
    ("Golang", "Go programming language", "language"),
    ("Kotlin", "programming language", "language"),
    ("Swift", "programming language", "language"),
    ("PHP", "programming language", "language"),
    ("Elixir", "programming language", "language"),
    ("Erlang", "programming language", "language"),
    ("Haskell", "programming language", "language"),
    ("Scala", "programming language", "language"),
    ("Clojure", "programming language", "language"),
    ("Lua", "programming language", "language"),
    ("OCaml", "programming language", "language"),
    ("F#", "programming language", "language"),
    ("Dart", "programming language", "language"),
    ("Solidity", "programming language", "language"),
    ("Zig", "programming language", "language"),
    ("Crystal", "programming language", "language"),
    # Web frameworks
    ("React", "JavaScript UI library", "framework"),
    ("Vue", "JavaScript framework", "framework"),
    ("Vue.js", "JavaScript framework", "framework"),
    ("Angular", "JavaScript framework", "framework"),
    ("Svelte", "JavaScript compiler/framework", "framework"),
    ("Next.js", "React framework", "framework"),
    ("Nuxt", "Vue framework", "framework"),
    ("SvelteKit", "Svelte framework", "framework"),
    ("Remix", "React framework", "framework"),
    ("Astro", "web framework", "framework"),
    ("Solid", "JavaScript UI library", "framework"),
    ("Qwik", "JavaScript framework", "framework"),
    ("Express", "Node.js framework", "framework"),
    ("Fastify", "Node.js framework", "framework"),
    ("NestJS", "Node.js framework", "framework"),
    ("Django", "Python framework", "framework"),
    ("Flask", "Python framework", "framework"),
    ("FastAPI", "Python framework", "framework"),
    ("Pyramid", "Python framework", "framework"),
    ("Rails", "Ruby on Rails framework", "framework"),
    ("Sinatra", "Ruby framework", "framework"),
    ("Laravel", "PHP framework", "framework"),
    ("Symfony", "PHP framework", "framework"),
    ("Spring", "Java framework", "framework"),
    ("Spring Boot", "Java framework", "framework"),
    ("ASP.NET", ".NET web framework", "framework"),
    ("Phoenix", "Elixir framework", "framework"),
    ("Gin", "Go web framework", "framework"),
    ("Echo", "Go web framework", "framework"),
    ("Fiber", "Go web framework", "framework"),
    ("Actix", "Rust web framework", "framework"),
    ("Axum", "Rust web framework", "framework"),
    ("Rocket", "Rust web framework", "framework"),
    # Databases
    ("PostgreSQL", "relational database", "database"),
    ("Postgres", "PostgreSQL", "database"),
    ("MySQL", "relational database", "database"),
    ("MariaDB", "relational database", "database"),
    ("SQLite", "embedded relational database", "database"),
    ("MongoDB", "NoSQL document database", "database"),
    ("Redis", "in-memory data store", "database"),
    ("Memcached", "memory cache", "database"),
    ("Elasticsearch", "search engine", "database"),
    ("Cassandra", "NoSQL database", "database"),
    ("DynamoDB", "AWS NoSQL database", "database"),
    ("Firestore", "Google NoSQL database", "database"),
    ("Firebase", "Google backend platform", "database"),
    ("Supabase", "Postgres-based BaaS", "database"),
    ("PlanetScale", "MySQL-compatible serverless DB", "database"),
    ("Neon", "Postgres serverless DB", "database"),
    ("CockroachDB", "distributed SQL database", "database"),
    ("ClickHouse", "columnar OLAP database", "database"),
    ("DuckDB", "in-process analytical DB", "database"),
    ("Snowflake", "cloud data warehouse", "database"),
    ("Databricks", "data platform", "database"),
    ("BigQuery", "Google analytical DB", "database"),
    ("Redshift", "AWS data warehouse", "database"),
    ("InfluxDB", "time series database", "database"),
    ("TimescaleDB", "Postgres time series extension", "database"),
    ("Couchbase", "NoSQL database", "database"),
    ("Neo4j", "graph database", "database"),
    ("Pinecone", "vector database", "database"),
    ("Weaviate", "vector database", "database"),
    ("Qdrant", "vector database", "database"),
    ("Chroma", "vector database", "database"),
    # Cloud / infra
    ("AWS", "Amazon Web Services", "cloud"),
    ("Amazon Web Services", "AWS", "cloud"),
    ("EC2", "AWS Elastic Compute Cloud", "cloud"),
    ("S3", "AWS Simple Storage Service", "cloud"),
    ("Lambda", "AWS serverless compute", "cloud"),
    ("DynamoDB", "AWS NoSQL", "cloud"),
    ("RDS", "AWS Relational Database Service", "cloud"),
    ("CloudFront", "AWS CDN", "cloud"),
    ("Route 53", "AWS DNS", "cloud"),
    ("VPC", "Virtual Private Cloud", "cloud"),
    ("EKS", "AWS Elastic Kubernetes Service", "cloud"),
    ("ECS", "AWS Elastic Container Service", "cloud"),
    ("Fargate", "AWS serverless containers", "cloud"),
    ("Azure", "Microsoft cloud", "cloud"),
    ("GCP", "Google Cloud Platform", "cloud"),
    ("Google Cloud", "GCP", "cloud"),
    ("Cloudflare", "CDN and edge platform", "cloud"),
    ("Cloudflare Workers", "Cloudflare edge compute", "cloud"),
    ("Cloudflare R2", "Cloudflare object storage", "cloud"),
    ("Cloudflare D1", "Cloudflare SQLite-compatible DB", "cloud"),
    ("Vercel", "frontend cloud platform", "cloud"),
    ("Netlify", "frontend cloud platform", "cloud"),
    ("Fly.io", "containerized cloud platform", "cloud"),
    ("Render", "cloud platform", "cloud"),
    ("Railway", "cloud platform", "cloud"),
    ("Heroku", "cloud platform", "cloud"),
    ("DigitalOcean", "cloud platform", "cloud"),
    ("Linode", "cloud platform", "cloud"),
    ("Hetzner", "cloud platform", "cloud"),
    # DevOps / containers
    ("Docker", "container platform", "devops"),
    ("Kubernetes", "container orchestration", "devops"),
    ("k8s", "Kubernetes", "devops"),
    ("kubectl", "Kubernetes CLI", "devops"),
    ("Helm", "Kubernetes package manager", "devops"),
    ("Terraform", "infrastructure as code", "devops"),
    ("Pulumi", "infrastructure as code", "devops"),
    ("Ansible", "configuration management", "devops"),
    ("Chef", "configuration management", "devops"),
    ("Puppet", "configuration management", "devops"),
    ("Jenkins", "CI/CD server", "devops"),
    ("GitHub Actions", "CI/CD service", "devops"),
    ("GitLab CI", "CI/CD service", "devops"),
    ("CircleCI", "CI/CD service", "devops"),
    ("Travis CI", "CI/CD service", "devops"),
    ("Bitbucket", "git hosting", "devops"),
    ("ArgoCD", "GitOps tool", "devops"),
    ("FluxCD", "GitOps tool", "devops"),
    ("Vagrant", "VM management", "devops"),
    ("Packer", "image building", "devops"),
    ("Nomad", "workload orchestration", "devops"),
    ("Consul", "service mesh", "devops"),
    ("Istio", "service mesh", "devops"),
    ("Linkerd", "service mesh", "devops"),
    ("Envoy", "service proxy", "devops"),
    ("Prometheus", "monitoring", "devops"),
    ("Grafana", "observability", "devops"),
    ("Datadog", "observability platform", "devops"),
    ("PagerDuty", "incident management", "devops"),
    ("Opsgenie", "incident management", "devops"),
    ("Sentry", "error tracking", "devops"),
    ("New Relic", "APM", "devops"),
    # Tools / editors
    ("VSCode", "Visual Studio Code", "tool"),
    ("Visual Studio Code", "Microsoft code editor", "tool"),
    ("IntelliJ", "JetBrains IDE", "tool"),
    ("PyCharm", "JetBrains Python IDE", "tool"),
    ("WebStorm", "JetBrains web IDE", "tool"),
    ("Vim", "text editor", "tool"),
    ("Neovim", "Vim fork", "tool"),
    ("Emacs", "text editor", "tool"),
    ("Sublime Text", "text editor", "tool"),
    ("Cursor", "AI-first code editor", "tool"),
    ("Zed", "code editor", "tool"),
    ("Xcode", "Apple IDE", "tool"),
    ("Android Studio", "Android IDE", "tool"),
    ("git", "version control", "tool"),
    ("GitHub", "git hosting", "tool"),
    ("GitLab", "git hosting", "tool"),
    ("npm", "Node package manager", "tool"),
    ("pnpm", "performant npm", "tool"),
    ("yarn", "Node package manager", "tool"),
    ("pip", "Python package manager", "tool"),
    ("uv", "Python package manager", "tool"),
    ("poetry", "Python dependency manager", "tool"),
    ("pipx", "Python app installer", "tool"),
    ("cargo", "Rust package manager", "tool"),
    ("Maven", "Java build tool", "tool"),
    ("Gradle", "build tool", "tool"),
    ("Bazel", "build tool", "tool"),
    ("Nx", "monorepo build tool", "tool"),
    ("Turborepo", "monorepo build tool", "tool"),
    ("Make", "build tool", "tool"),
    ("CMake", "build tool", "tool"),
    ("webpack", "module bundler", "tool"),
    ("Vite", "frontend build tool", "tool"),
    ("Rollup", "module bundler", "tool"),
    ("esbuild", "JS bundler", "tool"),
    ("Parcel", "module bundler", "tool"),
    ("Babel", "JS compiler", "tool"),
    ("ESLint", "JS linter", "tool"),
    ("Prettier", "code formatter", "tool"),
    ("Black", "Python formatter", "tool"),
    ("Ruff", "Python linter", "tool"),
    # AI / ML
    ("OpenAI", "AI company", "ai"),
    ("ChatGPT", "OpenAI chatbot", "ai"),
    ("GPT-4", "OpenAI model", "ai"),
    ("GPT-4o", "OpenAI model", "ai"),
    ("Claude", "Anthropic AI", "ai"),
    ("Anthropic", "AI company", "ai"),
    ("Gemini", "Google AI", "ai"),
    ("Bard", "Google AI", "ai"),
    ("Llama", "Meta open-weight LLM", "ai"),
    ("LLaMA", "Meta open-weight LLM", "ai"),
    ("Mistral", "AI company / model", "ai"),
    ("Qwen", "Alibaba open LLM", "ai"),
    ("DeepSeek", "Chinese AI company", "ai"),
    ("Whisper", "OpenAI speech-to-text model", "ai"),
    ("Stable Diffusion", "image generation", "ai"),
    ("Midjourney", "image generation", "ai"),
    ("DALL-E", "OpenAI image generation", "ai"),
    ("PyTorch", "ML framework", "ai"),
    ("TensorFlow", "ML framework", "ai"),
    ("JAX", "ML framework", "ai"),
    ("scikit-learn", "ML library", "ai"),
    ("Hugging Face", "AI model hub", "ai"),
    ("LangChain", "LLM framework", "ai"),
    ("LlamaIndex", "LLM data framework", "ai"),
    ("Cursor", "AI code editor", "ai"),
    ("Copilot", "GitHub AI pair programmer", "ai"),
    ("Codex", "OpenAI code model", "ai"),
    # Concepts
    ("REST", "Representational State Transfer", "concept"),
    ("GraphQL", "API query language", "concept"),
    ("gRPC", "Google RPC framework", "concept"),
    ("WebSocket", "full-duplex protocol", "concept"),
    ("HTTP", "HyperText Transfer Protocol", "concept"),
    ("HTTPS", "HTTP Secure", "concept"),
    ("TCP", "Transmission Control Protocol", "concept"),
    ("UDP", "User Datagram Protocol", "concept"),
    ("DNS", "Domain Name System", "concept"),
    ("SSH", "Secure Shell", "concept"),
    ("TLS", "Transport Layer Security", "concept"),
    ("SSL", "Secure Sockets Layer", "concept"),
    ("OAuth", "open authorization standard", "concept"),
    ("JWT", "JSON Web Token", "concept"),
    ("SAML", "Security Assertion Markup Language", "concept"),
    ("LDAP", "Lightweight Directory Access Protocol", "concept"),
    ("RBAC", "Role-Based Access Control", "concept"),
    ("ABAC", "Attribute-Based Access Control", "concept"),
    ("SSO", "Single Sign-On", "concept"),
    ("MFA", "Multi-Factor Authentication", "concept"),
    ("2FA", "Two-Factor Authentication", "concept"),
    ("CDN", "Content Delivery Network", "concept"),
    ("API", "Application Programming Interface", "concept"),
    ("SDK", "Software Development Kit", "concept"),
    ("ORM", "Object-Relational Mapping", "concept"),
    ("CRUD", "Create, Read, Update, Delete", "concept"),
    ("MVC", "Model-View-Controller", "concept"),
    ("MVVM", "Model-View-ViewModel", "concept"),
    ("DDD", "Domain-Driven Design", "concept"),
    ("TDD", "Test-Driven Development", "concept"),
    ("BDD", "Behavior-Driven Development", "concept"),
    ("CI/CD", "Continuous Integration / Continuous Deployment", "concept"),
    ("DevOps", "Development and Operations", "concept"),
    ("MLOps", "Machine Learning Operations", "concept"),
    ("SRE", "Site Reliability Engineering", "concept"),
    ("AIOps", "AI for IT Operations", "concept"),
    ("FinOps", "Cloud Financial Operations", "concept"),
    ("FaaS", "Function as a Service", "concept"),
    ("PaaS", "Platform as a Service", "concept"),
    ("IaaS", "Infrastructure as a Service", "concept"),
    ("SaaS", "Software as a Service", "concept"),
    ("BaaS", "Backend as a Service", "concept"),
    ("WASM", "WebAssembly", "concept"),
    ("WebAssembly", "binary instruction format", "concept"),
    ("CORS", "Cross-Origin Resource Sharing", "concept"),
    ("CSRF", "Cross-Site Request Forgery", "concept"),
    ("XSS", "Cross-Site Scripting", "concept"),
    ("SQL injection", "database attack", "concept"),
    ("DDoS", "Distributed Denial of Service", "concept"),
]


# Tech terms with non-obvious / community-standard pronunciations.
# Letter-form is auto-derived for ALL-CAPS acronyms; word-form is
# explicit for things Whisper consistently mishears.
_TECH_PRONUNCIATIONS: dict[str, list[str]] = {
    "AWS": ["ay double-u ess", "ay-double-u-ess"],
    "GCP": ["gee see pee"],
    "API": ["ay pee eye"],
    "SDK": ["ess dee kay"],
    "REST": ["rest"],
    "GraphQL": ["graph cue ell", "graph-q-l", "graph que ell"],
    "gRPC": ["gee ar pee see"],
    "HTTP": ["aitch tee tee pee"],
    "HTTPS": ["aitch tee tee pee ess"],
    "TCP": ["tee see pee"],
    "UDP": ["you dee pee"],
    "DNS": ["dee en ess"],
    "SSH": ["ess ess aitch"],
    "TLS": ["tee ell ess"],
    "SSL": ["ess ess ell"],
    "OAuth": ["oh auth", "oh-auth"],
    "JWT": ["jay double-u tee", "jot"],
    "SAML": ["sam ull", "sam-ull"],
    "LDAP": ["ell dap", "ell-dap"],
    "WASM": ["wazm", "wah-zm"],
    "CORS": ["kors"],
    "CSRF": ["sea surf", "see surf"],
    "XSS": ["ex ess ess"],
    "DDoS": ["dee dos", "dee-dos"],
    "MFA": ["em ef ay"],
    "2FA": ["two ef ay", "two-ef-ay"],
    "SSO": ["ess ess oh"],
    "RBAC": ["are back", "ar-back"],
    "ABAC": ["ay back", "ay-back"],
    "CDN": ["see dee en"],
    "ORM": ["oh ar em"],
    "CRUD": ["cruhd"],
    "MVC": ["em vee see"],
    "MVVM": ["em vee vee em"],
    "DDD": ["dee dee dee"],
    "TDD": ["tee dee dee"],
    "BDD": ["bee dee dee"],
    "CI/CD": ["see eye see dee", "see-eye see-dee"],
    "DevOps": ["dev ops"],
    "MLOps": ["em ell ops"],
    "SRE": ["ess ar ee"],
    "AIOps": ["ay eye ops"],
    "FinOps": ["fin ops"],
    "FaaS": ["fass"],
    "PaaS": ["pass"],
    "IaaS": ["eye ass", "eye-ass"],
    "SaaS": ["sass"],
    "BaaS": ["bass"],
    "WebAssembly": ["web assembly"],
    "k8s": ["kates", "kay eights"],
    "kubectl": ["cube cuttle", "cube control", "cube cuddle"],
    "kubelet": ["cube let", "kube-let"],
    "etcd": ["et see dee", "etsy dee"],
    "nginx": ["engine ex", "engine x"],
    "pnpm": ["pee enem", "pee en pee em"],
    "npm": ["en pee em"],
    "uv": ["you vee"],
    "pipx": ["pip ex", "pip-ex"],
    "Bazel": ["bay zel"],
    "PostgreSQL": ["postgres"],
    "MySQL": ["my ess cue ell", "my sequel"],
    "SQLite": ["sequel light", "ess cue ell light"],
    "Redis": ["red iss", "ree dis"],
    "DuckDB": ["duck dee bee"],
    "ClickHouse": ["click house"],
    "DALL-E": ["dolly", "dahl ee"],
    "GPT-4": ["gee pee tee four"],
    "GPT-4o": ["gee pee tee four oh"],
    "LLaMA": ["lah mah"],
    "Llama": ["lah mah"],
    "JAX": ["jax"],
    "Pyramid": ["pir-uh-mid"],  # Web framework, not the geometric one
}


def iter_terms() -> Iterable[RawTerm]:
    seen: set[str] = set()
    for canonical, gloss, subcat in _TERMS:
        key = canonical.lower()
        if key in seen:
            continue
        seen.add(key)
        # Build sounds_like:
        # - All-caps short acronyms (AWS, GCP, REST, SQL): auto + explicit hints
        # - Mixed-case names (Cloudflare, Postgres, Vercel): explicit hints only
        # - Underscored / dashed (Next.js, F-35): explicit hints only
        explicit = _TECH_PRONUNCIATIONS.get(canonical, [])
        if canonical.replace("-", "").replace("/", "").isalnum() and canonical.isupper() and 2 <= len(canonical) <= 6:
            sounds_like = derive_acronym_pronunciations(canonical, extra_hints=explicit)
        else:
            sounds_like = list(explicit)
        score = 0.7
        yield RawTerm(
            term=canonical,
            canonical_form=canonical,
            category="tech",
            subcategory=subcat,
            sounds_like=sounds_like,
            context_blurb=gloss[:140],
            popularity_score=score,
            source="Curated tech terms",
        )
    logger.info("Tech terms (curated): %d yielded", len(seen))


name = "Tech Terms (Curated)"
category = "tech"
